import React, {
  Suspense,
  memo,
  useCallback,
  useContext,
  useMemo,
} from "react";
import LoadingAnimation from "components/loader/LoadingAnimation";
import { VariableInputsContext } from "components/contexts/Contexts";
import PropTypes from "prop-types";
import clientPluginImports from "generated/clientPluginImports";

/**
 * ClientModuleLoader
 *
 * Loads React components from npm-installed client plugin packages
 * using a build-time import map generated by collectClientPlugins.js.
 *
 * The import map is keyed by source name (e.g., "chatbox_chart_panel"),
 * and each value is a () => import(...) function that webpack has already
 * resolved and code-split at build time.
 *
 * Passes variableInputValues and updateVariableInputValues to the
 * loaded component — same contract as ModuleLoader for custom MFEs.
 */

const componentCache = new Map();

function ClientModuleLoader({ source, props, visualizationRef }) {
  const { variableInputValues, setVariableInputValues } = useContext(
    VariableInputsContext,
  );

  const updateVariableInputValues = useCallback(
    (updatedValues) =>
      setVariableInputValues((prevStateValues) => ({
        ...prevStateValues,
        ...updatedValues,
      })),
    [setVariableInputValues],
  );

  const memoizedVariableInputValues = useMemo(
    () => variableInputValues,
    [variableInputValues],
  );

  const { Component, failed } = useMemo(() => {
    if (componentCache.has(source)) {
      return { Component: componentCache.get(source), failed: false };
    }

    const loader = clientPluginImports[source];
    if (!loader) {
      return { Component: null, failed: true };
    }

    const lazy = React.lazy(() =>
      loader().catch(() => {
        return { default: () => <h2>Failed to load: {source}</h2> };
      }),
    );
    componentCache.set(source, lazy);
    return { Component: lazy, failed: false };
  }, [source]);

  if (failed) {
    return (
      <h2>
        Client plugin not found: {source}
      </h2>
    );
  }

  return (
    <>
      {Component && (
        <Suspense fallback={<LoadingAnimation text="Loading..." />}>
          <Component
            {...props}
            ref={visualizationRef}
            variableInputValues={memoizedVariableInputValues}
            updateVariableInputValues={updateVariableInputValues}
          />
        </Suspense>
      )}
    </>
  );
}

ClientModuleLoader.propTypes = {
  source: PropTypes.string.isRequired,
  props: PropTypes.object,
  visualizationRef: PropTypes.oneOfType([
    PropTypes.func,
    PropTypes.shape({ current: PropTypes.any }),
  ]),
};

export default memo(ClientModuleLoader);
