export const CNRFCGauges = [
  {
    value: "CREC1",
    label: "CREC1 - SMITH RIVER - JEDEDIAH SMITH SP NEAR CRESCENT CITY",
  },
  { value: "FTDC1", label: "FTDC1 - SMITH RIVER - DOCTOR FINE BRIDGE" },
  { value: "ORIC1", label: "ORIC1 - REDWOOD CREEK - ORICK" },
  { value: "ARCC1", label: "ARCC1 - MAD RIVER - ARCATA" },
  { value: "PLBC1", label: "PLBC1 - EEL RIVER - LAKE PILLSBURY" },
  { value: "DOSC1", label: "DOSC1 - MIDDLE FORK EEL RIVER - DOS RIOS" },
  { value: "FTSC1", label: "FTSC1 - EEL RIVER - FORT SEWARD" },
  { value: "LEGC1", label: "LEGC1 - SOUTH FORK EEL RIVER - LEGGETT" },
  { value: "MRNC1", label: "MRNC1 - SOUTH FORK EEL RIVER - MIRANDA" },
  { value: "SCOC1", label: "SCOC1 - EEL RIVER - SCOTIA" },
  { value: "BRGC1", label: "BRGC1 - VAN DUZEN RIVER - BRIDGEVILLE" },
  { value: "FRNC1", label: "FRNC1 - EEL RIVER - FERNBRIDGE" },
  { value: "WKAO3", label: "WKAO3 - WILLIAMSON RIVER - KLAMATH AGENCY" },
  { value: "BTYO3", label: "BTYO3 - SPRAGUE RIVER - BEATTY" },
  { value: "SCNO3", label: "SCNO3 - SYCAN RIVER - BEATTY" },
  { value: "CHSO3", label: "CHSO3 - SPRAGUE RIVER - CHILOQUIN" },
  { value: "WMSO3", label: "WMSO3 - WILLIAMSON RIVER - CHILOQUIN" },
  {
    value: "KLAO3",
    label: "KLAO3 - KLAMATH RIVER - UPPER KLAMATH LAKE AT KLAMATH FALLS",
  },
  { value: "KEOO3", label: "KEOO3 - KLAMATH RIVER - KENO" },
  {
    value: "BOYO3",
    label: "BOYO3 - KLAMATH RIVER - BELOW JC BOYLE POWER PLANT",
  },
  { value: "IRGC1", label: "IRGC1 - KLAMATH RIVER - IRON GATE" },
  { value: "CKEC1", label: "CKEC1 - LOST RIVER - CLEAR LAKE" },
  { value: "GERO3", label: "GERO3 - MILLER CREEK - GERBER RESERVOIR" },
  { value: "YREC1", label: "YREC1 - SHASTA RIVER - YREKA" },
  { value: "FTJC1", label: "FTJC1 - SCOTT RIVER - FORT JONES" },
  { value: "SEIC1", label: "SEIC1 - KLAMATH RIVER - SEIAD VALLEY" },
  { value: "HAPC1", label: "HAPC1 - INDIAN CREEK - HAPPY CAMP" },
  { value: "SBRC1", label: "SBRC1 - SALMON RIVER - SOMES BAR" },
  { value: "ONSC1", label: "ONSC1 - KLAMATH RIVER - ORLEANS" },
  { value: "TCCC1", label: "TCCC1 - TRINITY RIVER - ABOVE COFFEE CREEK" },
  { value: "CEGC1", label: "CEGC1 - TRINITY RIVER - TRINITY LAKE" },
  { value: "TRJC1", label: "TRJC1 - TRINITY RIVER - JUNCTION CITY" },
  {
    value: "TRNC1",
    label: "TRNC1 - TRINITY RIVER - ABOVE NORTH FORK TRINITY RIVER",
  },
  { value: "BURC1", label: "BURC1 - TRINITY RIVER - BURNT RANCH" },
  { value: "HYMC1", label: "HYMC1 - SOUTH FORK TRINITY RIVER - HYAMPOM" },
  { value: "HOOC1", label: "HOOC1 - TRINITY RIVER - HOOPA" },
  { value: "KLMC1", label: "KLMC1 - KLAMATH RIVER - KLAMATH" },
  { value: "NVRC1", label: "NVRC1 - NAVARRO RIVER - NAVARRO" },
  { value: "UKAC1", label: "UKAC1 - RUSSIAN RIVER - UKIAH" },
  {
    value: "LAMC1",
    label: "LAMC1 - EAST FORK RUSSIAN RIVER - LAKE MENDOCINO",
  },
  { value: "HOPC1", label: "HOPC1 - RUSSIAN RIVER - HOPLAND" },
  { value: "CDLC1", label: "CDLC1 - RUSSIAN RIVER - CLOVERDALE" },
  { value: "BSCC1", label: "BSCC1 - BIG SULPHUR CREEK - CLOVERDALE" },
  { value: "GEYC1", label: "GEYC1 - RUSSIAN RIVER - GEYSERVILLE" },
  { value: "RMKC1", label: "RMKC1 - MAACAMA CREEK - KELLOGG" },
  { value: "HEAC1", label: "HEAC1 - RUSSIAN RIVER - HEALDSBURG" },
  { value: "WSDC1", label: "WSDC1 - DRY CREEK - LAKE SONOMA" },
  { value: "SSAC1", label: "SSAC1 - SANTA ROSA CREEK - SANTA ROSA" },
  { value: "CTIC1", label: "CTIC1 - LAGUNA DE SANTA ROSA - COATI" },
  { value: "LSEC1", label: "LSEC1 - LAGUNA DE SANTA ROSA - SEBASTOPOL" },
  { value: "MWEC1", label: "MWEC1 - MARK WEST CREEK - MIRABEL HEIGHTS" },
  { value: "RIOC1", label: "RIOC1 - RUSSIAN RIVER - HACIENDA BRIDGE" },
  { value: "GUEC1", label: "GUEC1 - RUSSIAN RIVER - GUERNEVILLE" },
  {
    value: "RROC1",
    label: "RROC1 - RUSSIAN RIVER - HIGHWAY 1 BRIDGE NEAR JENNER",
  },
  { value: "SHEC1", label: "SHEC1 - NAPA RIVER - SAINT HELENA" },
  { value: "APCC1", label: "APCC1 - NAPA RIVER - NAPA" },
  { value: "PRBC1", label: "PRBC1 - SALINAS RIVER - PASO ROBLES" },
  { value: "ESRC1", label: "ESRC1 - ESTRELLA RIVER - ESTRELLA" },
  { value: "NBYC1", label: "NBYC1 - NACIMIENTO RIVER - SAPAQUE" },
  { value: "NACC1", label: "NACC1 - NACIMIENTO RIVER - LAKE NACIMIENTO" },
  { value: "LWDC1", label: "LWDC1 - SAN ANTONIO RIVER - LOCKWOOD" },
  { value: "SNRC1", label: "SNRC1 - SAN ANTONIO RIVER - LAKE SAN ANTONIO" },
  { value: "BRDC1", label: "BRDC1 - SALINAS RIVER - BRADLEY" },
  { value: "KCYC1", label: "KCYC1 - SAN LORENZO CREEK - KING CITY" },
  { value: "SDDC1", label: "SDDC1 - SALINAS RIVER - SOLEDAD" },
  { value: "SOLC1", label: "SOLC1 - ARROYO SECO - SOLEDAD" },
  { value: "CHLC1", label: "CHLC1 - SALINAS RIVER - CHUALAR" },
  { value: "SPRC1", label: "SPRC1 - SALINAS RIVER - SPRECKELS" },
  { value: "BSRC1", label: "BSRC1 - BIG SUR RIVER - BIG SUR" },
  { value: "RDRC1", label: "RDRC1 - CARMEL RIVER - ROBLES DEL RIO" },
  { value: "PIIC1", label: "PIIC1 - SAN BENITO RIVER - WILLOW CREEK" },
  { value: "TESC1", label: "TESC1 - TRES PINOS CREEK - TRES PINOS" },
  {
    value: "HOSC1",
    label: "HOSC1 - SAN BENITO RIVER - HOSPITAL ROAD BRIDGE NEAR HOLLISTER",
  },
  { value: "PHOC1", label: "PHOC1 - PACHECO CREEK - DUNNEVILLE" },
  { value: "CBRC1", label: "CBRC1 - LLAGAS CREEK - CHESBRO RESERVOIR" },
  { value: "UVRC1", label: "UVRC1 - UVAS CREEK - UVAS RESERVOIR" },
  { value: "AROC1", label: "AROC1 - PAJARO RIVER - CHITTENDEN" },
  { value: "BTEC1", label: "BTEC1 - SAN LORENZO RIVER - BIG TREES" },
  { value: "COYC1", label: "COYC1 - COYOTE CREEK - COYOTE RESERVOIR" },
  { value: "ANDC1", label: "ANDC1 - COYOTE CREEK - ANDERSON RESERVOIR" },
  { value: "UPCC1", label: "UPCC1 - UPPER PENITENCIA CREEK - PIEDMOND ROAD" },
  { value: "CMIC1", label: "CMIC1 - COYOTE CREEK - MILPITAS AT HIGHWAY 237" },
  { value: "ALRC1", label: "ALRC1 - ALAMITOS CREEK - ALMADEN RESERVOIR" },
  { value: "CADC1", label: "CADC1 - CALERO CREEK - CALERO RESERVOIR" },
  { value: "GUAC1", label: "GUAC1 - GUADALUPE CREEK - GUADALUPE RESERVOIR" },
  {
    value: "GUDC1",
    label: "GUDC1 - GUADALUPE RIVER - SAN JOSE AT ALMADEN EXPRESSWAY",
  },
  { value: "LVKC1", label: "LVKC1 - ARROYO VALLE - DEL VALLE RESERVOIR" },
  { value: "LESC1", label: "LESC1 - LOS GATOS CREEK - LAKE ELSMAN" },
  { value: "LEXC1", label: "LEXC1 - LOS GATOS CREEK - LEXINGTON RESERVOIR" },
  { value: "AHOC1", label: "AHOC1 - ARROYO HONDO - SAN JOSE" },
  { value: "CVQC1", label: "CVQC1 - ARROYO HONDO - CALAVERAS RESERVOIR" },
  { value: "MPTC1", label: "MPTC1 - ALAMEDA CREEK - ABOVE DIVERSION DAM" },
  {
    value: "ANOC1",
    label: "ANOC1 - SAN ANTONIO CREEK - SAN ANTONIO RESERVOIR",
  },
  { value: "ALQC1", label: "ALQC1 - ALAMO CANAL - PLEASANTON" },
  { value: "ADLC1", label: "ADLC1 - ARROYO DE LA LAGUNA - VERONA" },
  { value: "AWEC1", label: "AWEC1 - ALAMEDA CREEK - SUNOL" },
  { value: "NILC1", label: "NILC1 - ALAMEDA CREEK - NILES" },
  { value: "LRZC1", label: "LRZC1 - SAN LORENZO CREEK - HAYWARD" },
  {
    value: "STDC1",
    label: "STDC1 - STEVENS CREEK - STEVENS CREEK RESERVOIR",
  },
  {
    value: "SFCC1",
    label: "SFCC1 - SAN FRANCISQUITO CREEK - STANFORD UNIVERSITY",
  },
  { value: "SSQC1", label: "SSQC1 - SISQUOC RIVER - SISQUOC" },
  { value: "GARC1", label: "GARC1 - SISQUOC RIVER - GAREY" },
  { value: "CYBC1", label: "CYBC1 - CUYAMA RIVER - BUCKHORN" },
  { value: "HSAC1", label: "HSAC1 - HUASNA RIVER - ARROYO GRANDE" },
  { value: "TWDC1", label: "TWDC1 - CUYAMA RIVER - TWITCHELL RESERVOIR" },
  { value: "LLYC1", label: "LLYC1 - SANTA YNEZ RIVER - LOS LAURELES" },
  { value: "CCHC1", label: "CCHC1 - SANTA YNEZ RIVER - LAKE CACHUMA" },
  { value: "SLUC1", label: "SLUC1 - SALSIPUEDES CREEK - LOMPOC" },
  { value: "NRWC1", label: "NRWC1 - SANTA YNEZ RIVER - NARROWS" },
  { value: "VRVC1", label: "VRVC1 - VENTURA RIVER - FOSTER PARK" },
  { value: "SCPC1", label: "SCPC1 - SANTA CLARA RIVER - PIRU" },
  { value: "SESC1", label: "SESC1 - SESPE CREEK - FILLMORE" },
  { value: "VCAC1", label: "VCAC1 - SANTA CLARA RIVER - VICTORIA AVENUE" },
  { value: "CLLC1", label: "CLLC1 - CALLEGUAS CREEK - CSU CHANNEL ISLANDS" },
  { value: "PYMC1", label: "PYMC1 - PIRU CREEK - PYRAMID LAKE" },
  { value: "LKPC1", label: "LKPC1 - PIRU CREEK - LAKE PIRU" },
  { value: "EFBC1", label: "EFBC1 - CASTAIC CREEK - ELDERBERRY FOREBAY" },
  { value: "CSKC1", label: "CSKC1 - CASTAIC CREEK - CASTAIC LAKE" },
  {
    value: "BTJC1",
    label: "BTJC1 - BIG TUJUNGA CREEK - BIG TUJUNGA RESERVOIR",
  },
  { value: "HANC1", label: "HANC1 - TUJUNGA WASH - HANSEN RESERVOIR" },
  { value: "SRWC1", label: "SRWC1 - SANTA ANA RIVER - SEVEN OAKS RESERVOIR" },
  { value: "TIMC1", label: "TIMC1 - SAN TIMOTEO CREEK - LOMA LINDA" },
  { value: "YTLC1", label: "YTLC1 - LYTLE CREEK - COLTON" },
  {
    value: "SREC1",
    label: "SREC1 - SANTA ANA RIVER - SAN BERNARDINO AT E STREET",
  },
  { value: "KNBC1", label: "KNBC1 - CAJON CREEK - KEENBROOK" },
  {
    value: "MWXC1",
    label: "MWXC1 - SANTA ANA RIVER - MUNICIPAL WATER DISTRICT CROSSING",
  },
  { value: "TSLC1", label: "TSLC1 - TEMESCAL CREEK - CORONA" },
  { value: "ADOC1", label: "ADOC1 - SANTA ANA RIVER - PRADO RESERVOIR" },
  { value: "TEKC1", label: "TEKC1 - TEMECULA CREEK - AGUANGA" },
  { value: "VLKC1", label: "VLKC1 - TEMECULA CREEK - VAIL LAKE" },
  { value: "MUTC1", label: "MUTC1 - MURRIETA CREEK - TEMECULA" },
  { value: "SMHC1", label: "SMHC1 - SANTA MARGARITA RIVER - TEMECULA" },
  { value: "YDRC1", label: "YDRC1 - SANTA MARGARITA - YSIDORA" },
  { value: "HAWC1", label: "HAWC1 - SAN LUIS REY RIVER - LAKE HENSHAW" },
  {
    value: "SUDC1",
    label: "SUDC1 - SANTA YSABEL CREEK - SUTHERNLAND RESERVOIR",
  },
  { value: "HODC1", label: "HODC1 - SAN DIEGUITO RIVER - LAKE HODGES" },
  { value: "SHRC1", label: "SHRC1 - SAN LUIS REY RIVER - SHEARER CROSSING" },
  { value: "SLOC1", label: "SLOC1 - SAN LUIS REY RIVER - OCEANSIDE" },
  { value: "ELPC1", label: "ELPC1 - SAN DIEGO RIVER - EL CAPITAN RESERVOIR" },
  {
    value: "SVIC1",
    label: "SVIC1 - SAN VINCENTE CREEK - SAN VICENTE RESERVOIR",
  },
  { value: "FSNC1", label: "FSNC1 - SAN DIEGO RIVER - FASHION VALLEY" },
  { value: "BRTC1", label: "BRTC1 - COTTONWOOD CREEK - BARRETT LAKE" },
  { value: "PCNC1", label: "PCNC1 - PALM CANYON CREEK - PALM SPRINGS" },
  { value: "WWIC1", label: "WWIC1 - WHITEWATER RIVER - RANCHO MIRAGE" },
  { value: "DEPC1", label: "DEPC1 - DEEP CREEK - PALM DESERT" },
  { value: "WTIC1", label: "WTIC1 - WHITEWATER RIVER - INDIO" },
  { value: "DKHC1", label: "DKHC1 - DEEP CREEK - HESPERIA" },
  {
    value: "SVWC1",
    label: "SVWC1 - WEST FORK MOJAVE RIVER - SILVERWOOD LAKE",
  },
  { value: "WFMC1", label: "WFMC1 - WEST FORK MOJAVE RIVER - HESPERIA" },
  { value: "MVDC1", label: "MVDC1 - MOJAVE RIVER - MOJAVE FORKS RESERVOIR" },
  { value: "MVVC1", label: "MVVC1 - MOJAVE RIVER - VICTORVILLE" },
  { value: "MBRC1", label: "MBRC1 - MOJAVE RIVER - BARSTOW" },
  { value: "PLYC1", label: "PLYC1 - SOUTH FORK PIT RIVER - LIKELY" },
  { value: "CNBC1", label: "CNBC1 - PIT RIVER - CANBY" },
  { value: "PITC1", label: "PITC1 - PIT RIVER - MONTGOMERY CREEK" },
  { value: "MMCC1", label: "MMCC1 - MCCLOUD RIVER - MCCLOUD" },
  { value: "MSSC1", label: "MSSC1 - MCCLOUD RIVER - SHASTA LAKE" },
  { value: "DLTC1", label: "DLTC1 - SACRAMENTO RIVER - DELTA" },
  { value: "SHDC1", label: "SHDC1 - SACRAMENTO RIVER - SHASTA LAKE" },
  { value: "WHSC1", label: "WHSC1 - CLEAR CREEK - WHISKEYTOWN RESERVOIR" },
  { value: "RDGC1", label: "RDGC1 - CLEAR CREEK - IGO" },
  { value: "CWCC1", label: "CWCC1 - COW CREEK - MILLVILLE" },
  { value: "COTC1", label: "COTC1 - BATTLE CREEK - COTTONWOOD" },
  { value: "CWAC1", label: "CWAC1 - COTTONWOOD CREEK - COTTONWOOD" },
  { value: "BDBC1", label: "BDBC1 - SACRAMENTO RIVER - BEND BRIDGE" },
  { value: "RDBC1", label: "RDBC1 - SACRAMENTO RIVER - RED BLUFF" },
  { value: "MLMC1", label: "MLMC1 - MILL CREEK - LOS MOLINOS" },
  { value: "EDCC1", label: "EDCC1 - ELDER CREEK - PASKENTA" },
  { value: "TEHC1", label: "TEHC1 - SACRAMENTO RIVER - TEHAMA BRIDGE" },
  { value: "TCRC1", label: "TCRC1 - THOMES CREEK - PASKENTA" },
  { value: "DCVC1", label: "DCVC1 - DEER CREEK - VINA" },
  { value: "VWBC1", label: "VWBC1 - SACRAMENTO RIVER - VINA WOODSON BRIDGE" },
  { value: "HAMC1", label: "HAMC1 - SACRAMENTO RIVER - HAMILTON CITY" },
  { value: "HKCC1", label: "HKCC1 - BIG CHICO CREEK - CHICO" },
  {
    value: "EPRC1",
    label: "EPRC1 - LITTLE STONY CREEK - EAST PARK RESERVOIR",
  },
  { value: "SGEC1", label: "SGEC1 - STONY CREEK - STONY GORGE RESERVOIR" },
  { value: "BLBC1", label: "BLBC1 - STONY CREEK - BLACK BUTTE RESERVOIR" },
  { value: "ORFC1", label: "ORFC1 - SACRAMENTO RIVER - ORD FERRY" },
  { value: "BTCC1", label: "BTCC1 - SACRAMENTO RIVER - BUTTE CITY" },
  { value: "CLSC1", label: "CLSC1 - SACRAMENTO RIVER - MOULTON WEIR" },
  { value: "CLAC1", label: "CLAC1 - SACRAMENTO RIVER - COLUSA WEIR" },
  { value: "CLUC1", label: "CLUC1 - SACRAMENTO RIVER - COLUSA BRIDGE" },
  { value: "BKCC1", label: "BKCC1 - BUTTE CREEK - CHICO" },
  { value: "TISC1", label: "TISC1 - SACRAMENTO RIVER - TISDALE WEIR" },
  { value: "WLKC1", label: "WLKC1 - SACRAMENTO RIVER - WILKINS SLOUGH" },
  { value: "FMWC1", label: "FMWC1 - SACRAMENTO RIVER - FREMONT WEIR" },
  { value: "NCOC1", label: "NCOC1 - FEATHER RIVER - NICOLAUS" },
  { value: "VONC1", label: "VONC1 - SACRAMENTO RIVER - VERONA" },
  {
    value: "SAMC1",
    label: "SAMC1 - AMERICAN RIVER - SACRAMENTO AT H STREET",
  },
  {
    value: "SACC1",
    label: "SACC1 - SACRAMENTO RIVER - SACRAMENTO AT I STREET",
  },
  { value: "PLLC1", label: "PLLC1 - NORTH FORK FEATHER RIVER - PRATTVILLE" },
  { value: "IIFC1", label: "IIFC1 - INDIAN CREEK - INDIAN FALLS" },
  { value: "SCBC1", label: "SCBC1 - SPANISH CREEK - KEDDIE" },
  { value: "NFEC1", label: "NFEC1 - NORTH FORK FEATHER RIVER - EAST BRANCH" },
  { value: "MFTC1", label: "MFTC1 - MIDDLE FORK FEATHER RIVER - PORTOLA" },
  { value: "ANTC1", label: "ANTC1 - INDIAN CREEK - ANTELOPE LAKE" },
  { value: "DVSC1", label: "DVSC1 - BIG GRIZZLY CREEK - LAKE DAVIS" },
  {
    value: "FHDC1",
    label: "FHDC1 - LITTLE LAST CHANCE CREEK - FRENCHMAN LAKE",
  },
  { value: "MRMC1", label: "MRMC1 - MIDDLE FORK FEATHER RIVER - MERRIMAC" },
  { value: "WBGC1", label: "WBGC1 - WEST BRANCH FEATHER RIVER - MAGALIA" },
  { value: "ORDC1", label: "ORDC1 - FEATHER RIVER - LAKE OROVILLE" },
  { value: "YUBC1", label: "YUBC1 - FEATHER RIVER - YUBA CITY" },
  { value: "GYRC1", label: "GYRC1 - NORTH YUBA RIVER - GOODYEARS BAR" },
  {
    value: "NBBC1",
    label: "NBBC1 - NORTH FORK YUBA RIVER - NEW BULLARDS BAR RESERVOIR",
  },
  {
    value: "JKRC1",
    label: "JKRC1 - MIDDLE FORK YUBA RIVER - JACKSON MEADOWS RESERVOIR",
  },
  { value: "OURC1", label: "OURC1 - MIDDLE FORK YUBA RIVER - OUR HOUSE" },
  { value: "FOCC1", label: "FOCC1 - FORDYCE CREEK - FORDYCE LAKE" },
  { value: "SUAC1", label: "SUAC1 - SOUTH FORK YUBA RIVER - LAKE SPAULDING" },
  { value: "BWKC1", label: "BWKC1 - CANYON CREEK - BOWMAN RESERVOIR" },
  { value: "JNSC1", label: "JNSC1 - SOUTH FORK YUBA RIVER - JONES BAR" },
  { value: "DCSC1", label: "DCSC1 - DEER CREEK - SMARTSVILLE" },
  { value: "DMCC1", label: "DMCC1 - DRY CREEK - MERLE COLLINS RESERVOIR" },
  { value: "SOVC1", label: "SOVC1 - DEER CREEK - SCOTTS FLAT RESERVOIR" },
  { value: "ROLC1", label: "ROLC1 - BEAR RIVER - ROLLINS LAKE" },
  { value: "CFWC1", label: "CFWC1 - BEAR RIVER - CAMP FAR WEST RESERVOIR" },
  { value: "HLEC1", label: "HLEC1 - YUBA RIVER - ENGLEBRIGHT RESERVOIR" },
  { value: "MRYC1", label: "MRYC1 - YUBA RIVER - MARYSVILLE" },
  { value: "MUPC1", label: "MUPC1 - MIDDLE CREEK - UPPER LAKE" },
  { value: "SKPC1", label: "SKPC1 - SCOTTS CREEK - LAKEPORT" },
  { value: "KCVC1", label: "KCVC1 - KELSEY CREEK - KELSEYVILLE" },
  { value: "CLKC1", label: "CLKC1 - CLEAR LAKE - LAKEPORT" },
  { value: "HOUC1", label: "HOUC1 - NORTH FORK CACHE CREEK - HOUGH SPRINGS" },
  {
    value: "INVC1",
    label: "INVC1 - NORTH FORK CACHE CREEK - INDIAN VALLEY RESERVOIR",
  },
  { value: "HCHC1", label: "HCHC1 - BEAR CREEK - HOLSTEN CHIMNEY CANYON" },
  { value: "RMSC1", label: "RMSC1 - CACHE CREEK - RUMSEY" },
  { value: "YLOC1", label: "YLOC1 - CACHE CREEK - YOLO" },
  { value: "PCGC1", label: "PCGC1 - PUTAH CREEK - GUENOC" },
  { value: "LBEC1", label: "LBEC1 - PUTAH CREEK - LAKE BERRYESSA" },
  {
    value: "NFDC1",
    label: "NFDC1 - NORTH FORK AMERICAN RIVER - NORTH FORK DAM",
  },
  {
    value: "FMDC1",
    label: "FMDC1 - MIDDLE FORK AMERICAN RIVER - FRENCH MEADOWS RESERVOIR",
  },
  {
    value: "MFPC1",
    label: "MFPC1 - MIDDLE FORK AMERICAN RIVER - ABOVE MIDDLE FORK POWERHOUSE",
  },
  { value: "LNLC1", label: "LNLC1 - GERLE CREEK - LOON LAKE" },
  { value: "RUFC1", label: "RUFC1 - RUBICON RIVER - FORESTHILL" },
  {
    value: "NMFC1",
    label: "NMFC1 - NORTH FORK OF MIDDLE FORK AMERICAN RIVER - FORESTHILL",
  },
  {
    value: "SPYC1",
    label: "SPYC1 - PILOT CREEK - ABOVE STUMPY MEADOWS RESERVOIR",
  },
  { value: "RBBC1", label: "RBBC1 - RUBICON RIVER - ROCKBOUND LAKE" },
  { value: "HLLC1", label: "HLLC1 - RUBICON RIVER - HELL HOLE RESERVOIR" },
  {
    value: "MFAC1",
    label: "MFAC1 - MIDDLE FORK AMERICAN RIVER - FORESTHILL",
  },
  { value: "AKYC1", label: "AKYC1 - SOUTH FORK AMERICAN RIVER - KYBURZ" },
  { value: "UNVC1", label: "UNVC1 - SILVER CREEK - UNION VALLEY RESERVOIR" },
  {
    value: "ICHC1",
    label: "ICHC1 - SOUTH FORK SILVER CREEK - ICE HOUSE RESERVOIR",
  },
  { value: "SVCC1", label: "SVCC1 - SILVER CREEK - CAMINO RESERVOIR" },
  {
    value: "CBAC1",
    label: "CBAC1 - SOUTH FORK AMERICAN RIVER - CHILI BAR RESERVOIR",
  },
  { value: "FOLC1", label: "FOLC1 - AMERICAN RIVER - FOLSOM LAKE" },
  {
    value: "SACC0",
    label: "SACC0 - SACRAMENTO VALLEY - WATER RESOURCES INDEX",
  },
  {
    value: "VNSC0",
    label: "VNSC0 - SAN JOAQUIN VALLEY - WATER RESOURCES INDEX",
  },
  { value: "MLIC0", label: "MLIC0 - CENTRAL VALLEY - WATER RESOURCES INDEX" },
  { value: "KKVC1", label: "KKVC1 - KERN RIVER - FAIRVIEW DAM" },
  { value: "KRVC1", label: "KRVC1 - KERN RIVER - KERNVILLE" },
  { value: "SKRC1", label: "SKRC1 - SOUTH FORK KERN RIVER - ONYX" },
  { value: "ISAC1", label: "ISAC1 - KERN RIVER - LAKE ISABELLA" },
  { value: "DKCC1", label: "DKCC1 - DEER CREEK - FOUNTAIN SPRINGS" },
  {
    value: "TVRC1",
    label: "TVRC1 - SOUTH FORK TULE RIVER - RESERVATION BOUNDARY",
  },
  { value: "SCSC1", label: "SCSC1 - TULE RIVER - LAKE SUCCESS" },
  { value: "KTRC1", label: "KTRC1 - KAWEAH RIVER - THREE RIVERS" },
  { value: "TMDC1", label: "TMDC1 - KAWEAH RIVER - LAKE KAWEAH" },
  { value: "DLMC1", label: "DLMC1 - DRY CREEK - LEMONCOVE" },
  {
    value: "KGPC1",
    label: "KGPC1 - SOUTH FORK KINGS RIVER - ABOVE BOYDEN CAVERN",
  },
  { value: "PFTC1", label: "PFTC1 - KINGS RIVER - PINE FLAT RESERVOIR" },
  { value: "MLPC1", label: "MLPC1 - MILL CREEK - PIEDRA" },
  { value: "WARC1", label: "WARC1 - WARTHAN CREEK - COALINGA" },
  { value: "LGCC1", label: "LGCC1 - LOS GATOS CREEK - COALINGA" },
  { value: "LGAC1", label: "LGAC1 - LOS GATOS CREEK - EL DORADO AVENUE" },
  {
    value: "PNEC1",
    label: "PNEC1 - PANOCHE CREEK - INTERSTATE 5 OVERCROSSING",
  },
  { value: "LBDC1", label: "LBDC1 - LOS BANOS CREEK - LOS BANOS RESERVOIR" },
  {
    value: "FRAC1",
    label: "FRAC1 - SAN JOAQUIN RIVER - MILLERTON RESERVOIR",
  },
  { value: "LTDC1", label: "LTDC1 - LITTLE DRY CREEK - FRIANT" },
  { value: "HIDC1", label: "HIDC1 - FRESNO RIVER - HENSLEY LAKE" },
  { value: "BHNC1", label: "BHNC1 - CHOWCHILLA RIVER - BUCHANAN RESERVOIR" },
  { value: "MPAC1", label: "MPAC1 - MARIPOSA CREEK - MARIPOSA RESERVOIR" },
  { value: "OWCC1", label: "OWCC1 - OWENS CREEK - OWENS RESERVOIR" },
  { value: "BCKC1", label: "BCKC1 - BEAR CREEK - BEAR RESERVOIR" },
  { value: "BNCC1", label: "BNCC1 - BURNS CREEK - BURNS CREEK RESERVOIR" },
  { value: "MEEC1", label: "MEEC1 - BEAR CREEK - MCKEE ROAD" },
  { value: "HPIC1", label: "HPIC1 - MERCED RIVER - HAPPY ISLES" },
  {
    value: "POHC1",
    label: "POHC1 - MERCED RIVER - YOSEMITE AT POHONO BRIDGE",
  },
  { value: "EXQC1", label: "EXQC1 - MERCED RIVER - EXCHEQUER RESERVOIR" },
  { value: "DSNC1", label: "DSNC1 - DRY CREEK - SNELLING" },
  { value: "STVC1", label: "STVC1 - MERCED RIVER - STEVINSON" },
  { value: "OREC1", label: "OREC1 - ORESTIMBA CREEK - NEWMAN" },
  { value: "NWMC1", label: "NWMC1 - SAN JOAQUIN RIVER - NEWMAN" },
  { value: "PATC1", label: "PATC1 - SAN JOAQUIN RIVER - PATTERSON" },
  { value: "PTTC1", label: "PTTC1 - DEL PUERTO CREEK - PATTERSON" },
  {
    value: "HETC1",
    label: "HETC1 - TUOLUMNE RIVER - HETCH HETCHY RESERVOIR",
  },
  { value: "LNRC1", label: "LNRC1 - ELEANOR CREEK - LAKE ELEANOR" },
  { value: "CHVC1", label: "CHVC1 - CHERRY CREEK - CHERRY LAKE" },
  {
    value: "NDPC1",
    label: "NDPC1 - TUOLUMNE RIVER - NEW DON PEDRO RESERVOIR",
  },
  { value: "DCMC1", label: "DCMC1 - DRY CREEK - MODESTO" },
  { value: "MDSC1", label: "MDSC1 - TUOLUMNE RIVER - MODESTO" },
  {
    value: "NSWC1",
    label: "NSWC1 - HIGHLAND CREEK - NEW SPICER MEADOWS RESERVOIR",
  },
  {
    value: "NDVC1",
    label: "NDVC1 - NORTH FORK STANISLAUS RIVER - DIVERSION DAM",
  },
  { value: "AVYC1", label: "AVYC1 - NORTH FORK STANISLAUS RIVER - AVERY" },
  {
    value: "NMSC1",
    label: "NMSC1 - STANISLAUS RIVER - NEW MELONES RESERVOIR",
  },
  { value: "OBBC1", label: "OBBC1 - STANISLAUS RIVER - ORANGE BLOSSOM" },
  { value: "RIPC1", label: "RIPC1 - STANISLAUS RIVER - RIPON" },
  { value: "VNSC1", label: "VNSC1 - SAN JOAQUIN RIVER - VERNALIS" },
  { value: "MSGC1", label: "MSGC1 - MORMON SLOUGH - BELLOTA" },
  {
    value: "FRGC1",
    label: "FRGC1 - LITTLEJOHNS CREEK - FARMINGTON RESERVOIR",
  },
  { value: "NHGC1", label: "NHGC1 - CALAVERAS RIVER - NEW HOGAN RESERVOIR" },
  { value: "CMPC1", label: "CMPC1 - MOKELUMNE RIVER - PARDEE RESERVOIR" },
  { value: "SOSC1", label: "SOSC1 - MIDDLE FORK COSUMNES RIVER - SOMERSET" },
  { value: "EDOC1", label: "EDOC1 - NORTH FORK COSUMNES RIVER - EL DORADO" },
  { value: "MHBC1", label: "MHBC1 - COSUMNES RIVER - MICHIGAN BAR" },
  { value: "MCNC1", label: "MCNC1 - COSUMNES RIVER - MCCONNELL" },
  { value: "SUSC1", label: "SUSC1 - SUSAN RIVER - SUSANVILLE" },
  { value: "TAHC1", label: "TAHC1 - LAKE TAHOE INFLOW - TAHOE BASIN" },
  { value: "THLC1", label: "THLC1 - LAKE TAHOE - TAHOE CITY" },
  { value: "TRCC1", label: "TRCC1 - TRUCKEE RIVER - TRUCKEE" },
  { value: "DNRC1", label: "DNRC1 - DONNER CREEK - DONNER LAKE" },
  { value: "MTSC1", label: "MTSC1 - MARTIS CREEK - MARTIS CREEK LAKE" },
  { value: "PSRC1", label: "PSRC1 - PROSSER CREEK - PROSSER RESERVOIR" },
  { value: "ILAC1", label: "ILAC1 - INDEPENDENCE CREEK - INDEPENDENCE LAKE" },
  { value: "SGNC1", label: "SGNC1 - SAGEHEN CREEK - TRUCKEE" },
  {
    value: "STPC1",
    label: "STPC1 - LITTLE TRUCKEE RIVER - STAMPEDE RESERVOIR",
  },
  { value: "BCAC1", label: "BCAC1 - LITTLE TRUCKEE RIVER - BOCA RESERVOIR" },
  { value: "FARC1", label: "FARC1 - TRUCKEE RIVER - FARAD" },
  { value: "TRRN2", label: "TRRN2 - TRUCKEE RIVER - RENO" },
  { value: "LWON2", label: "LWON2 - STEAMBOAT CREEK - LITTLE WASHOE LAKE" },
  { value: "SCRN2", label: "SCRN2 - STEAMBOAT CREEK - STEAMBOAT" },
  { value: "SCWN2", label: "SCWN2 - STEAMBOAT CREEK - SPARKS" },
  { value: "VISN2", label: "VISN2 - TRUCKEE RIVER - VISTA" },
  { value: "TBDN2", label: "TBDN2 - TRUCKEE RIVER - BELOW DERBY DAM" },
  { value: "WADN2", label: "WADN2 - TRUCKEE RIVER - WADSWORTH" },
  { value: "WOOC1", label: "WOOC1 - WEST FORK CARSON RIVER - WOODFORDS" },
  { value: "CEMC1", label: "CEMC1 - EAST FORK CARSON RIVER - MARKLEEVILLE" },
  { value: "GRDN2", label: "GRDN2 - EAST FORK CARSON RIVER - GARDNERVILLE" },
  { value: "STWN2", label: "STWN2 - CARSON RIVER - CARSON CITY" },
  { value: "FTCN2", label: "FTCN2 - CARSON RIVER - FORT CHURCHILL" },
  {
    value: "WWBC1",
    label:
      "WWBC1 - WEST WALKER RIVER - BELOW LITTLE WALKER RIVER NEAR COLEVILLE",
  },
  { value: "TOPN2", label: "TOPN2 - WEST WALKER RIVER - TOPAZ LAKE" },
  { value: "HOYN2", label: "HOYN2 - WEST WALKER RIVER - HOYE BRIDGE" },
  { value: "WWHN2", label: "WWHN2 - WEST WALKER RIVER - HUDSON" },
  {
    value: "BPRC1",
    label: "BPRC1 - EAST WALKER RIVER - BRIDGEPORT RESERVOIR",
  },
  {
    value: "EWSN2",
    label: "EWSN2 - EAST WALKER RIVER - ABOVE STROSNIDER DITCH",
  },
  { value: "MASN2", label: "MASN2 - WALKER RIVER - MASON AT SNYDER LANE" },
  { value: "MHSN2", label: "MHSN2 - MARYS RIVER - ABOVE HOT SPRINGS CREEK" },
  { value: "LCLN2", label: "LCLN2 - LAMOILLE CREEK - LAMOILLE" },
  {
    value: "DEVN2",
    label: "DEVN2 - NORTH FORK HUMBOLDT RIVER - DEVILS GATE",
  },
  { value: "HREN2", label: "HREN2 - HUMBOLDT RIVER - ELKO" },
  {
    value: "DIXN2",
    label: "DIXN2 - SOUTH FORK HUMBOLDT RIVER - DIXIE CREEK",
  },
  { value: "HRCN2", label: "HRCN2 - HUMBOLDT RIVER - CARLIN" },
  { value: "PALN2", label: "PALN2 - HUMBOLDT RIVER - PALISADE" },
  { value: "ROCN2", label: "ROCN2 - ROCK CREEK - BATTLE MOUNTAIN" },
  { value: "HBMN2", label: "HBMN2 - HUMBOLDT RIVER - BATTLE MOUNTAIN" },
  { value: "CMSN2", label: "CMSN2 - HUMBOLDT RIVER - COMUS" },
  { value: "MARN2", label: "MARN2 - MARTIN CREEK - PARADISE VALLEY" },
  { value: "HRIN2", label: "HRIN2 - HUMBOLDT RIVER - IMLAY" },
  { value: "MDCN2", label: "MDCN2 - MCDERMITT CREEK - MCDERMITT" },
];
