"""
TethysDash MCP Server

Exposes tools for creating native TethysDash visualizations (Plotly charts,
tables, maps, cards, text) and rendering registered MFE components.

The LLM calls these tools to create dashboard grid items with inline data -
no backend API call needed. The chatbox dispatches the returned specs as
DOM events that DashboardLayout.js handles.

Usage:
    python -m tethysapp.tethysdash.mcp.tethysdash_mcp_server

Connects to chatbox via MCP SSE transport on port 9001.
"""

import logging
import os
import json
import uuid
from typing import Optional, Dict, Any, List, Union
from typing_extensions import Annotated
from pydantic import Field
from fastmcp import FastMCP
from fastmcp.server.transforms.search import BM25SearchTransform
from starlette.middleware import Middleware
from starlette.middleware.cors import CORSMiddleware
from starlette.responses import Response as StarletteResponse
import requests as http_requests

mcp = FastMCP(
    "TethysDash MCP Server",
    transforms=[
        BM25SearchTransform(
            max_results=5,
            always_visible=[
                "create_plotly_chart",
                "create_data_table",
                "create_variable_input",
                "create_map_visualization",
                "add_map_service_layer",
                "render_plugin",
                "render_custom_visualization",
                "list_available_visualizations",
                "list_intake_plugins",
            ],
        ),
    ],
)
LOGGER = logging.getLogger("tethysdash.mcp")
TETHYSDASH_BASE_URL = os.getenv("TETHYSDASH_BASE_URL", "http://localhost:8080/apps/tethysdash")


def _patch_sse_transport_for_cors():
    """Monkey-patch SseServerTransport.handle_post_message to handle OPTIONS.

    MCP SDK v1.26+ validates Content-Type on all requests routed to
    handle_post_message, including CORS preflight OPTIONS (which have no
    Content-Type). This patch intercepts OPTIONS and returns 200 with
    CORS headers before the SDK's validation runs.
    """
    from mcp.server.sse import SseServerTransport

    original_handle = SseServerTransport.handle_post_message

    async def patched_handle(self, scope, receive, send):
        if scope.get("method") == "OPTIONS":
            origin = dict(scope.get("headers", [])).get(b"origin", b"").decode()
            headers = {
                "access-control-allow-origin": origin or "*",
                "access-control-allow-methods": "GET, POST, OPTIONS",
                "access-control-allow-headers": "content-type, x-csrftoken, authorization",
                "access-control-allow-credentials": "true",
                "access-control-max-age": "86400",
            }
            response = StarletteResponse(status_code=200, headers=headers)
            await response(scope, receive, send)
            return
        await original_handle(self, scope, receive, send)

    SseServerTransport.handle_post_message = patched_handle

_patch_sse_transport_for_cors()


CORS_MIDDLEWARE = [
    Middleware(
        CORSMiddleware,
        allow_origins=["*"],
        allow_methods=["*"],
        allow_headers=["*"],
    ),
]

# ---------------------------------------------------------------------------
# Client plugin registry (loaded from collectClientPlugins.js output)
# ---------------------------------------------------------------------------

def _load_client_plugin_registry() -> List[Dict[str, Any]]:
    """Load the client plugin registry generated by collectClientPlugins.js."""
    registry_path = os.path.normpath(os.path.join(
        os.path.dirname(__file__), "..", "..", "..",
        "reactapp", "generated", "clientPluginRegistry.json"
    ))
    try:
        with open(registry_path, "r") as f:
            registry = json.load(f)
        LOGGER.info("Loaded %d client plugin(s) from %s", len(registry), registry_path)
        return registry
    except FileNotFoundError:
        LOGGER.warning("Client plugin registry not found: %s", registry_path)
        return []
    except json.JSONDecodeError as e:
        LOGGER.warning("Invalid JSON in client plugin registry: %s", e)
        return []


CLIENT_PLUGIN_REGISTRY = _load_client_plugin_registry()


def _load_runtime_plugin_registry() -> List[Dict[str, Any]]:
    """Load the runtime plugin registry synced from browser localStorage."""
    registry_path = os.path.normpath(os.path.join(
        os.path.dirname(__file__), "..", "..", "..",
        "reactapp", "generated", "runtimePluginRegistry.json"
    ))
    try:
        with open(registry_path, "r") as f:
            registry = json.load(f)
        LOGGER.info("Loaded %d runtime plugin(s) from %s", len(registry), registry_path)
        return registry
    except FileNotFoundError:
        return []
    except json.JSONDecodeError as e:
        LOGGER.warning("Invalid JSON in runtime plugin registry: %s", e)
        return []


def _get_all_plugins() -> List[Dict[str, Any]]:
    """Return combined static + runtime registries, re-reading runtime from disk."""
    runtime = _load_runtime_plugin_registry()
    combined = CLIENT_PLUGIN_REGISTRY + runtime
    LOGGER.info(
        "Plugin registries: %d static + %d runtime = %d total",
        len(CLIENT_PLUGIN_REGISTRY), len(runtime), len(combined),
    )
    return combined


def _convert_arg_to_schema(arg_name: str, arg_spec) -> Dict[str, Any]:
    """Convert a tethysdash plugin arg type to a structured schema."""
    if isinstance(arg_spec, list):
        return {"type": "string", "enum": arg_spec}
    if arg_spec == "text":
        return {"type": "string"}
    if arg_spec == "number":
        return {"type": "number"}
    if arg_spec == "checkbox":
        return {"type": "boolean", "default": False}
    if arg_spec == "object":
        return {"type": "object"}
    if arg_spec == "array":
        return {"type": "array"}
    if isinstance(arg_spec, dict):
        return arg_spec  # pass through rich declarations as-is
    return {"type": "string", "description": f"Input type: {arg_spec}"}


def _convert_plugin_args_to_schema(args: Dict) -> Dict[str, Any]:
    """Convert all args for a plugin to structured schemas."""
    return {name: _convert_arg_to_schema(name, spec) for name, spec in args.items()}


# ---------------------------------------------------------------------------
# Built-in visualization tools
# ---------------------------------------------------------------------------

@mcp.tool(
    name="create_plotly_chart",
    description="Create an interactive Plotly chart on the dashboard",
    tags=["visualization", "chart"],
)
def create_plotly_chart(
    data: Annotated[List[Dict[str, Any]], Field(description="Plotly trace objects. Each dict should have 'x', 'y', and optionally 'type', 'name', 'mode', etc.")],
    layout: Annotated[Optional[Dict[str, Any]], Field(description="Plotly layout object with title, axis labels, etc.")] = None,
    config: Annotated[Optional[Dict[str, Any]], Field(description="Plotly config object (responsive, displaylogo, etc.)")] = None,
    title: Annotated[Optional[str], Field(description="Chart title (shorthand - added to layout.title)")] = None,
    w: Annotated[int, Field(description="Grid width in columns (out of 100)")] = 50,
    h: Annotated[int, Field(description="Grid height in row units (each unit ~10px at 1920px)")] = 40,
) -> Dict[str, Any]:
    """Create a Plotly chart visualization on the dashboard.

    Returns a visualization spec that the chatbox dispatches as a grid item.
    The chart renders using TethysDash's native BasePlot component.
    """
    final_layout = layout or {}
    if title and "title" not in final_layout:
        final_layout["title"] = title

    final_config = config or {"responsive": True, "displaylogo": False}

    return {
        "visualization": {
            "source": "Inline Plotly",
            "vizType": "plotly",
            "inlineData": {
                "data": data,
                "layout": final_layout,
                "config": final_config,
            },
            "w": w,
            "h": h,
        }
    }


@mcp.tool(
    name="create_data_table",
    description="Create a data table on the dashboard",
    tags=["visualization", "table"],
)
def create_data_table(
    data: Annotated[List[Dict[str, Any]], Field(description="Array of row objects, e.g. [{'col1': 'val1', 'col2': 'val2'}, ...]")],
    title: Annotated[Optional[str], Field(description="Table title")] = None,
    subtitle: Annotated[Optional[str], Field(description="Table subtitle")] = None,
    w: Annotated[int, Field(description="Grid width in columns (out of 100)")] = 50,
    h: Annotated[int, Field(description="Grid height in row units (each unit ~10px at 1920px)")] = 35,
) -> Dict[str, Any]:
    """Create a data table visualization on the dashboard.

    Returns a visualization spec that renders using TethysDash's native DataTable component.
    """
    return {
        "visualization": {
            "source": "Inline Table",
            "vizType": "table",
            "inlineData": {
                "data": data,
                "title": title or "",
                "subtitle": subtitle or "",
            },
            "w": w,
            "h": h,
        }
    }


@mcp.tool(
    name="create_card",
    description="Create a card with title, description, and value on the dashboard",
    tags=["visualization", "card"],
)
def create_card(
    title: Annotated[str, Field(description="Card title")],
    description: Annotated[Optional[str], Field(description="Card description text")] = None,
    data: Annotated[Optional[Any], Field(description="Card data (value, metric, etc.)")] = None,
    w: Annotated[int, Field(description="Grid width in columns (out of 100)")] = 25,
    h: Annotated[int, Field(description="Grid height in row units")] = 15,
) -> Dict[str, Any]:
    """Create a card visualization on the dashboard.

    Cards display a title, description, and optional data value.
    Renders using TethysDash's native Card component.
    """
    return {
        "visualization": {
            "source": "Inline Card",
            "vizType": "card",
            "inlineData": {
                "title": title,
                "description": description or "",
                "data": data,
            },
            "w": w,
            "h": h,
        }
    }


@mcp.tool(
    name="create_text",
    description="Create a text content block on the dashboard",
    tags=["visualization", "text"],
)
def create_text(
    text: Annotated[str, Field(description="Text content to display")],
    w: Annotated[int, Field(description="Grid width in columns (out of 100)")] = 50,
    h: Annotated[int, Field(description="Grid height in row units")] = 15,
) -> Dict[str, Any]:
    """Create a text visualization on the dashboard.

    Renders using TethysDash's native Text component.
    """
    return {
        "visualization": {
            "source": "Text",
            "args": {
                "text": text,
            },
            "w": w,
            "h": h,
        }
    }


@mcp.tool(
    name="create_custom_image",
    description="Display an image from a URL on the dashboard",
    tags=["visualization", "image"],
)
def create_custom_image(
    image_url: Annotated[str, Field(description="URL of the image to display (http/https URL, data URI, or S3 path)")],
    alt_text: Annotated[Optional[str], Field(description="Alt text for accessibility")] = None,
    w: Annotated[int, Field(description="Grid width in columns (out of 100)")] = 50,
    h: Annotated[int, Field(description="Grid height in row units (each unit ~10px at 1920px)")] = 30,
) -> Dict[str, Any]:
    """Create a custom image visualization on the dashboard.

    Displays an image from a URL. Renders using TethysDash's native Image component.
    """
    return {
        "visualization": {
            "source": "Custom Image",
            "args": {
                "image_source": image_url,
            },
            "w": w,
            "h": h,
        }
    }


BASE_MAPS = {
    "light_gray": "https://server.arcgisonline.com/arcgis/rest/services/Canvas/World_Light_Gray_Base/MapServer",
    "dark_gray": "https://server.arcgisonline.com/arcgis/rest/services/Canvas/World_Dark_Gray_Base/MapServer",
    "topo": "https://server.arcgisonline.com/arcgis/rest/services/World_Topo_Map/MapServer",
    "imagery": "https://server.arcgisonline.com/arcgis/rest/services/World_Imagery/MapServer",
    "streets": "https://server.arcgisonline.com/arcgis/rest/services/World_Street_Map/MapServer",
    "terrain": "https://server.arcgisonline.com/arcgis/rest/services/World_Terrain_Base/MapServer",
    "ocean": "https://server.arcgisonline.com/arcgis/rest/services/Ocean/World_Ocean_Base/MapServer",
}

NOMINATIM_URL = "https://nominatim.openstreetmap.org/search"
NOMINATIM_USER_AGENT = "TethysDash/1.0 (tethysdash@aquaveo.com)"


def _geocode(place_name):
    """Geocode a place name to (lon, lat) via Nominatim."""
    resp = http_requests.get(
        NOMINATIM_URL,
        params={"q": place_name, "format": "json", "limit": 1},
        headers={"User-Agent": NOMINATIM_USER_AGENT},
        timeout=10,
    )
    resp.raise_for_status()
    results = resp.json()
    if not results:
        return None
    return float(results[0]["lon"]), float(results[0]["lat"])


def _build_markers_layer(markers):
    """Build a GeoJSON VectorLayer configuration from a list of marker dicts."""
    features = []
    for m in markers:
        props = {}
        if m.get("label"):
            props["label"] = m["label"]
        features.append({
            "type": "Feature",
            "geometry": {
                "type": "Point",
                "coordinates": [m["lon"], m["lat"]],
            },
            "properties": props,
        })
    geojson = {
        "type": "FeatureCollection",
        "crs": {"type": "name", "properties": {"name": "EPSG:4326"}},
        "features": features,
    }
    return {
        "configuration": {
            "type": "VectorLayer",
            "props": {
                "name": "Markers",
                "source": {"type": "GeoJSON", "props": {}, "geojson": geojson},
            },
        }
    }


@mcp.tool(
    name="create_map_visualization",
    description=(
        "Create a geographic map visualization on the dashboard. "
        "Supports markers, drawing tools, and dashboard variable integration. "
        "Use 'center' for place names or 'map_extent' for explicit coordinates. "
        "To add WMS, ESRI, GeoJSON, or other service layers, call add_map_service_layer "
        "with the returned map UUID."
    ),
    tags=["visualization", "map", "geographic", "location", "marker", "layer"],
)
def create_map_visualization(
    markers: Annotated[Optional[List[Dict[str, Any]]], Field(description=(
        "Simple point markers as [{\"lon\": <number>, \"lat\": <number>, \"label\": \"<text>\"}]. "
        "The server auto-builds a GeoJSON VectorLayer with correct CRS. "
        "Use this for quick markers instead of constructing full GeoJSON layer configs."
    ))] = None,
    center: Annotated[Optional[str], Field(description=(
        "Place name to center the map on (geocoded via Nominatim). "
        "Ignored when map_extent is provided."
    ))] = None,
    base_map: Annotated[Optional[str], Field(description=(
        "Base map shorthand or full ArcGIS MapServer URL. "
        "Shorthands: 'streets', 'imagery', 'topo', 'light_gray', 'dark_gray', 'terrain', 'ocean'. "
        "Any ArcGIS MapServer URL also works directly. Null for no base map."
    ))] = "streets",
    map_extent: Annotated[Optional[str], Field(description=(
        "Map extent as comma-separated coordinates in EPSG:4326 (lon/lat). "
        "Center+zoom: 'lon,lat,zoom'. Bounding box: 'minLon,minLat,maxLon,maxLat'. "
        "Takes precedence over 'center' when both are provided."
    ))] = None,
    zoom: Annotated[int, Field(description="Zoom level (1=world, 12=city, 18=street)")] = 12,
    layer_control: Annotated[bool, Field(description="Show layer visibility control panel")] = False,
    drawing_tools: Annotated[Optional[List[str]], Field(description=(
        "Drawing tool types to enable: 'Point', 'LineString', 'Polygon', 'Rectangle'. "
        "Null to disable drawing."
    ))] = None,
    drawing_limit: Annotated[int, Field(description="Max drawn features (0 = unlimited)")] = 0,
    drawing_variable: Annotated[Optional[str], Field(description=(
        "Dashboard variable name to publish drawn geometries to."
    ))] = None,
    extent_variable: Annotated[Optional[str], Field(description=(
        "Dashboard variable name to publish map extent on pan/zoom."
    ))] = None,
    w: Annotated[int, Field(description="Grid width in columns (out of 100)")] = 50,
    h: Annotated[int, Field(description="Grid height in row units")] = 45,
) -> Dict[str, Any]:
    """Create a geographic map on the dashboard.

    Simple usage: provide 'center' or 'markers' for a quick map.
    For service layers (WMS, ESRI, GeoJSON, KML): call add_map_service_layer
    with the returned map UUID after creating the map.
    """
    map_uuid = str(uuid.uuid4())
    LOGGER.info("create_map_visualization: uuid=%s, center=%s, markers=%s",
                map_uuid, center, markers is not None)

    # Resolve base map
    resolved_base_map = BASE_MAPS.get(base_map, base_map) if base_map else None

    # Build layers array from markers only (service layers added via add_map_service_layer)
    all_layers = []
    if markers:
        all_layers.append(_build_markers_layer(markers))

    # Resolve center via geocoding
    resolved_extent = None
    if map_extent:
        resolved_extent = {"extent": map_extent, "projection": "EPSG:4326"}
    elif center:
        coords = _geocode(center)
        if coords is None:
            return {"error": f"Could not geocode '{center}'. Try providing explicit coordinates via map_extent."}
        lon, lat = coords
        resolved_extent = {"extent": f"{lon},{lat},{zoom}", "projection": "EPSG:4326"}
    elif markers:
        # Auto-center on first marker
        lon, lat = markers[0]["lon"], markers[0]["lat"]
        resolved_extent = {"extent": f"{lon},{lat},{zoom}", "projection": "EPSG:4326"}

    # Add extent variable if requested
    if extent_variable and resolved_extent:
        resolved_extent["variable"] = extent_variable

    # Build drawing config
    map_drawing = None
    if drawing_tools:
        map_drawing = {"options": drawing_tools, "limit": drawing_limit}
        if drawing_variable:
            map_drawing["variable_name"] = drawing_variable

    # Build args matching the manual UI's format — only include keys with
    # actual values. The edit modal's checkAllInputs treats null as "unfilled"
    # and blocks save. mapConfig is not a registry arg (frontend generates it).
    args = {
        "baseMap": resolved_base_map,
        "layers": all_layers,
        "layerControl": layer_control,
    }
    if resolved_extent:
        args["map_extent"] = resolved_extent
    if map_drawing:
        args["mapDrawing"] = map_drawing

    return {
        "visualization": {
            "source": "Map",
            "uuid": map_uuid,
            "args": args,
            "w": w,
            "h": h,
        },
        "map_uuid": map_uuid,
        "message": f"Map created (uuid: {map_uuid}). Use add_map_service_layer with this UUID to add WMS, ESRI, GeoJSON, or other service layers.",
    }


# ---------------------------------------------------------------------------
# Map service layer tool
# ---------------------------------------------------------------------------

VALID_SOURCE_TYPES = [
    "WMS",
    "ESRI Image and Map Service",
    "ESRI Feature Service",
    "GeoJSON",
    "KML",
    "Image Tile",
    "Vector Tile",
    "PMTiles Vector",
    "PMTiles Raster",
]

SOURCE_TYPE_TO_LAYER_TYPE = {
    "WMS": "ImageLayer",
    "ESRI Image and Map Service": "ImageLayer",
    "ESRI Feature Service": "VectorLayer",
    "GeoJSON": "VectorLayer",
    "KML": "VectorLayer",
    "Image Tile": "TileLayer",
    "Vector Tile": "VectorTileLayer",
    "PMTiles Vector": "VectorTileLayer",
    "PMTiles Raster": "WebGLTile",
}


def _resolve_esri_layer_name(url: str, layer_id: Optional[str]) -> Optional[str]:
    """Fetch the ESRI service's actual layer name for the given layer index.

    The manual map editor uses the service's layer name as the
    attributeVariables key (via getImageArcGISRestLayerAttributes).  The ESRI
    /identify response also returns this name as ``layerName``.  Using the
    service name — not the client display name — ensures the click-time
    attribute variable lookup matches.

    Returns None on any failure so the caller can fall back to the display name.
    """
    if layer_id is None:
        return None

    # Parse numeric layer index from layer_id (e.g., "show:0" → 0, "0" → 0)
    index_str = layer_id.split(":")[-1] if ":" in layer_id else layer_id
    try:
        layer_index = int(index_str)
    except (ValueError, TypeError):
        return None

    try:
        resp = http_requests.get(f"{url}?f=json", timeout=5)
        resp.raise_for_status()
        service_info = resp.json()
        layers = service_info.get("layers", [])
        for layer in layers:
            if layer.get("id") == layer_index:
                return layer.get("name")
        return None
    except Exception as exc:
        LOGGER.warning(
            "Failed to resolve ESRI layer name from %s (layer_id=%s): %s",
            url, layer_id, exc,
        )
        return None


@mcp.tool(
    name="add_map_service_layer",
    description=(
        "Add a WMS, ESRI, GeoJSON, KML, or tile service layer to an existing "
        "map created by create_map_visualization"
    ),
    tags=["map", "layer", "geographic"],
)
def add_map_service_layer(
    map_uuid: Annotated[str, Field(description="UUID returned by create_map_visualization")],
    source_type: Annotated[str, Field(description=(
        "Layer source type. One of: WMS, ESRI Image and Map Service, "
        "ESRI Feature Service, GeoJSON, KML, Image Tile, Vector Tile, "
        "PMTiles Vector, PMTiles Raster"
    ))],
    name: Annotated[str, Field(description="Display name for the layer in the layer control")],
    url: Annotated[Optional[str], Field(description=(
        "Service URL. Required for all source types except GeoJSON."
    ))] = None,
    layer_id: Annotated[Optional[str], Field(description=(
        "Layer identifier within the service. "
        "For ESRI Image and Map Service: visibility directive for params.LAYERS. "
        "For ESRI Feature Service: integer layer index as a string."
    ))] = None,
    wms_layers: Annotated[Optional[str], Field(description=(
        "WMS LAYERS parameter value in workspace:layer format. "
        "Required when source_type is WMS."
    ))] = None,
    geojson: Annotated[Optional[Union[Dict[str, Any], str]], Field(description=(
        "Inline GeoJSON FeatureCollection or Feature object. "
        "Required when source_type is GeoJSON and no geojson_url is provided. "
        "CRS is auto-assigned if missing."
    ))] = None,
    geojson_url: Annotated[Optional[str], Field(description=(
        "URL to a GeoJSON file. Use instead of inline geojson when the data "
        "is hosted externally. The frontend fetches the URL at render time."
    ))] = None,
    queryable: Annotated[bool, Field(description=(
        "Enable click-to-query on this layer"
    ))] = False,
    attribute_variables: Annotated[Optional[Union[Dict[str, str], str]], Field(description=(
        "Maps feature attribute names to dashboard variable names. "
        "When a feature is clicked, attribute values are published to the "
        "corresponding dashboard variables."
    ))] = None,
    params: Annotated[Optional[Union[Dict[str, Any], str]], Field(description=(
        "Additional source parameters merged into the source props. "
        "Supports ${variable_name} syntax for dashboard variable references."
    ))] = None,
    opacity: Annotated[Optional[float], Field(description="Layer opacity from 0 (transparent) to 1 (opaque)")] = None,
    min_zoom: Annotated[Optional[int], Field(description="Minimum zoom level at which the layer is visible")] = None,
    max_zoom: Annotated[Optional[int], Field(description="Maximum zoom level at which the layer is visible")] = None,
) -> Dict[str, Any]:
    """Add a service layer to an existing map.

    Constructs the OpenLayers layer configuration from flat, source-type-specific
    parameters and returns a layer_update result (not a visualization).
    The chatbox dispatches this as a tethysdash:update-visualization event.
    """
    LOGGER.info(
        "add_map_service_layer: map_uuid=%s, source_type=%s, name=%s",
        map_uuid, source_type, name,
    )

    # Coerce JSON strings to dicts — some LLM providers serialize object
    # arguments as strings instead of parsed objects.
    if isinstance(geojson, str):
        geojson = json.loads(geojson)
    if isinstance(attribute_variables, str):
        attribute_variables = json.loads(attribute_variables)
    if isinstance(params, str):
        params = json.loads(params)

    # Validate source_type
    if source_type not in VALID_SOURCE_TYPES:
        return {
            "error": (
                f"Invalid source_type '{source_type}'. "
                f"Valid types: {', '.join(VALID_SOURCE_TYPES)}"
            )
        }

    extra_params = params or {}

    # Validate required fields per source type
    if source_type == "WMS":
        if not url or not wms_layers:
            return {"error": "source_type 'WMS' requires 'url' and 'wms_layers' parameters"}
    elif source_type == "ESRI Image and Map Service":
        if not url:
            return {"error": "source_type 'ESRI Image and Map Service' requires 'url' parameter"}
    elif source_type == "ESRI Feature Service":
        if not url or not layer_id:
            return {"error": "source_type 'ESRI Feature Service' requires 'url' and 'layer_id' parameters"}
    elif source_type == "GeoJSON":
        if not geojson and not geojson_url:
            return {"error": "source_type 'GeoJSON' requires 'geojson' or 'geojson_url' parameter"}
    elif source_type == "KML":
        if not url:
            return {"error": "source_type 'KML' requires 'url' parameter"}
    elif source_type == "Image Tile":
        if not url:
            return {"error": "source_type 'Image Tile' requires 'url' parameter"}
    elif source_type == "Vector Tile":
        if not url:
            return {"error": "source_type 'Vector Tile' requires 'url' parameter"}
    elif source_type == "PMTiles Vector":
        if not url:
            return {"error": "source_type 'PMTiles Vector' requires 'url' parameter"}
    elif source_type == "PMTiles Raster":
        if not url:
            return {"error": "source_type 'PMTiles Raster' requires 'url' parameter"}

    # Build source props based on source_type
    source_props = {}

    if source_type == "WMS":
        wms_params = {"LAYERS": wms_layers}
        wms_params.update(extra_params)
        source_props = {"url": url, "params": wms_params}

    elif source_type == "ESRI Image and Map Service":
        esri_params = {}
        if layer_id:
            esri_params["LAYERS"] = layer_id
        esri_params.update(extra_params)
        source_props = {"url": url}
        if esri_params:
            source_props["params"] = esri_params

    elif source_type == "ESRI Feature Service":
        source_props = {"url": url, "layer": int(layer_id)}
        source_props.update(extra_params)

    elif source_type == "GeoJSON":
        # GeoJSON goes on the source object directly (not under props).
        # This matches the manual UI format (MapLayer.js:246) and is what
        # loadLayerJSONs (utilities.js:1029) and ModuleLoader.loadGeoJSON
        # both expect: source.geojson, not source.props.geojson.
        if geojson_url:
            # URL string — the frontend fetches it at render time via
            # loadGeoJSON in utilities.js (the geojson.includes("/") branch).
            geojson_with_crs = geojson_url
        else:
            # Inline data — auto-assign CRS if missing
            geojson_with_crs = dict(geojson)
            if "crs" not in geojson_with_crs:
                geojson_with_crs["crs"] = {
                    "type": "name",
                    "properties": {"name": "EPSG:4326"},
                }
        source_props = {}

    elif source_type == "KML":
        source_props = {"url": url}

    elif source_type == "Image Tile":
        source_props = {"url": url}

    elif source_type == "Vector Tile":
        source_props = {"urls": url}

    elif source_type in ("PMTiles Vector", "PMTiles Raster"):
        source_props = {"url": url}

    # Build the layer configuration
    layer_type = SOURCE_TYPE_TO_LAYER_TYPE[source_type]
    source_config = {
        "type": source_type,
        "props": source_props,
    }
    # GeoJSON data lives at source.geojson (top-level), not source.props.geojson.
    # loadLayerJSONs and ModuleLoader.loadGeoJSON both read it from this location.
    if source_type == "GeoJSON" and geojson_with_crs:
        source_config["geojson"] = geojson_with_crs
    props_dict = {
        "name": name,
        "source": source_config,
    }

    # Add optional layer props
    if opacity is not None:
        props_dict["opacity"] = opacity
    if min_zoom is not None:
        props_dict["minZoom"] = min_zoom
    if max_zoom is not None:
        props_dict["maxZoom"] = max_zoom

    layer_config = {
        "configuration": {
            "type": layer_type,
            "props": props_dict,
        }
    }

    # Add queryable flag
    if queryable:
        layer_config["queryable"] = True

    # Add attribute variables.
    # For ESRI Image and Map Service, the attributeVariables key must be the
    # ESRI service's layer name (returned by /identify), not the client
    # display name.  This matches how the manual map editor stores the key.
    if attribute_variables:
        attr_key = name
        if source_type == "ESRI Image and Map Service":
            resolved = _resolve_esri_layer_name(url, layer_id)
            if resolved:
                attr_key = resolved
            else:
                LOGGER.warning(
                    "Could not resolve ESRI layer name; falling back to display name '%s'",
                    name,
                )
        layer_config["attributeVariables"] = {attr_key: attribute_variables}

    return {
        "layer_update": {
            "map_uuid": map_uuid,
            "layer": layer_config,
        }
    }


# ---------------------------------------------------------------------------
# Variable input + intake plugin tools
# ---------------------------------------------------------------------------

@mcp.tool(
    name="create_variable_input",
    description="Create an interactive variable input that other visualizations can reference with ${variable_name} syntax",
    tags=["dashboard", "variable"],
)
def create_variable_input(
    variable_name: Annotated[str, Field(description="Variable name used in ${...} references by other visualizations")],
    variable_type: Annotated[str, Field(description=(
        "Input type: 'text', 'number', 'checkbox', 'date', 'dropdown', "
        "'slider', 'date-range', or 'csv-uploader'"
    ))] = "text",
    initial_value: Annotated[str, Field(description="Default value for the variable input")] = "",
    options: Annotated[Optional[Union[List[str], str]], Field(description=(
        "Options for dropdown type. Provide as a comma-separated string "
        "or a list of strings."
    ))] = None,
    slider_min: Annotated[Optional[float], Field(description="Minimum value for slider type")] = None,
    slider_max: Annotated[Optional[float], Field(description="Maximum value for slider type")] = None,
    slider_step: Annotated[Optional[float], Field(description="Step increment for slider type")] = None,
    w: Annotated[int, Field(description="Grid width in columns (out of 100)")] = 25,
    h: Annotated[int, Field(description="Grid height in row units")] = 12,
) -> Dict[str, Any]:
    """Create a variable input on the dashboard.

    Variable inputs are interactive controls (text fields, dropdowns, sliders)
    that other visualizations can reference using ${variable_name} syntax.
    When the user changes the input, all linked visualizations auto-refresh.
    To link a plugin to this variable, call list_intake_plugins to get the source name,
    then render_plugin with args referencing ${variable_name}.
    """
    valid_types = [
        "text", "number", "checkbox", "date",
        "dropdown", "slider", "date-range", "csv-uploader",
    ]
    if variable_type not in valid_types:
        return {"error": f"Invalid variable_type '{variable_type}'. Must be one of: {valid_types}"}

    # Coerce string options to list (LLMs may pass "A,B,C" instead of ["A","B","C"])
    if isinstance(options, str):
        options = [o.strip() for o in options.split(",")]

    # Validate type-specific requirements
    if variable_type == "dropdown" and not options:
        return {"error": "variable_type 'dropdown' requires the 'options' parameter"}
    if variable_type == "slider" and (slider_min is None or slider_max is None):
        return {"error": "variable_type 'slider' requires 'slider_min' and 'slider_max' parameters"}

    LOGGER.info("create_variable_input: name=%s, type=%s, initial=%s", variable_name, variable_type, initial_value)

    args = {
        "variable_name": variable_name,
        "initial_value": initial_value,
    }

    if variable_type == "dropdown":
        # Dropdown: variable_options_source is the array of option strings.
        # The frontend renders a select/dropdown when it receives an array.
        args["variable_options_source"] = options
    elif variable_type == "slider":
        args["variable_options_source"] = "slider"
        # Slider metadata goes in the dotted key that Base.js reads at line 336:
        # metadata: args["variable_options_source.metadata"]
        try:
            initial_num = float(initial_value) if initial_value else slider_min
        except (ValueError, TypeError):
            initial_num = slider_min
        args["variable_options_source.metadata"] = {
            "min": slider_min,
            "max": slider_max,
            "step": slider_step or 1,
            "dataType": "Number",
            "initialValue": initial_num,
            "outputFormat": "{{n}}",
        }
    else:
        args["variable_options_source"] = variable_type

    return {
        "visualization": {
            "source": "Variable Input",
            "vizType": "variableInput",
            "args": args,
            "w": w,
            "h": h,
        }
    }


@mcp.tool(
    name="list_intake_plugins",
    description="List all installed backend plugins. Returns source (intake driver name), label, type, and argument names for each plugin. Use the 'source' field when calling render_plugin.",
    tags=["discovery", "plugin"],
)
def list_intake_plugins() -> Dict[str, Any]:
    """List all installed Python intake-driver plugins available in TethysDash.

    Returns a compact list of plugins with:
    - source: the intake driver name (USE THIS in render_plugin)
    - label: display name
    - type: visualization type (plotly, table, map, etc.)
    - arg_names: list of argument names the plugin accepts

    IMPORTANT: When calling render_plugin, use the 'source' field,
    NOT the 'label' field. The source is the Python driver name that
    the backend uses to instantiate the plugin.

    Note: Requires the TethysDash Django server to be running.
    """
    try:
        response = http_requests.get(
            f"{TETHYSDASH_BASE_URL}/visualizations/list/",
            timeout=10,
        )
        response.raise_for_status()
        data = response.json()
        # Django API returns {"visualizations": [...groups...]}, not a bare list
        groups = data.get("visualizations", []) if isinstance(data, dict) else data if isinstance(data, list) else []
        LOGGER.info("list_intake_plugins: fetched %d groups with %d total plugins",
                     len(groups),
                     sum(len(g.get("options", [])) for g in groups if isinstance(g, dict)))

        # Return compact format: source + label + type + arg names only.
        # Full argument schemas are large (~10-100KB) and cause the result
        # to be truncated, preventing the LLM from seeing all plugins.
        compact = []
        for group in groups:
            options = group.get("options", []) if isinstance(group, dict) else []
            for opt in options:
                entry = {
                    "source": opt.get("source", ""),
                    "label": opt.get("label", ""),
                    "type": opt.get("type", ""),
                }
                # Extract just argument names from the args schema
                args = opt.get("args", {})
                if isinstance(args, dict):
                    entry["arg_names"] = list(args.keys())
                compact.append(entry)

        return {"intake_plugins": compact}
    except http_requests.RequestException as e:
        LOGGER.error("Failed to fetch intake plugins from Django: %s", e)
        return {"error": f"Failed to fetch intake plugins from TethysDash: {e}"}


@mcp.tool(
    name="render_plugin",
    description=(
        "Create a visualization using an installed backend plugin. "
        "Call list_intake_plugins first to discover available plugins and their args. "
        "Use the 'source' field from the results. "
        "To link to a dashboard variable input, use ${variable_name} syntax in arg values — "
        "the visualization auto-refreshes when the variable changes."
    ),
    tags=["dashboard", "plugin"],
)
def render_plugin(
    source: Annotated[str, Field(description="Intake driver name from the 'source' field in list_intake_plugins results. Always call list_intake_plugins first to get the exact source name. Do NOT guess or invent source names — using a wrong name causes a 'not installed' error.")],
    args: Annotated[Dict[str, Any], Field(description="Plugin arguments. Use ${variable_name} syntax to reference dashboard variable inputs. Example: {\"gauge_id\": \"${my_gauge}\"}")],
    w: Annotated[int, Field(description="Grid width in columns (out of 100)")] = 50,
    h: Annotated[int, Field(description="Grid height in row units")] = 25,
) -> Dict[str, Any]:
    """Create a visualization using a Python intake-driver plugin.

    IMPORTANT: Always call list_intake_plugins first to get the exact source name.
    The source parameter must match the 'source' field from list_intake_plugins results.
    Using a wrong or guessed name causes a 'Visualization is not installed' error.

    Args can reference variable inputs using ${variable_name} syntax —
    when the referenced variable changes, the visualization auto-refreshes.
    """
    LOGGER.info("render_plugin: source=%s, args=%s", source, args)

    return {
        "visualization": {
            "source": source,
            "vizType": "intake_plugin",
            "args": args,
            "w": w,
            "h": h,
        }
    }


# ---------------------------------------------------------------------------
# MFE rendering tools
# ---------------------------------------------------------------------------

# Hidden from LLM — not registered as an MCP tool.
# Kept as internal function for backward compatibility.
# Can be re-exposed later via BM25SearchTransform.
def render_mfe(
    url: Annotated[str, Field(description="URL to the MFE's remoteEntry.js")],
    scope: Annotated[str, Field(description="Module Federation scope name")],
    module: Annotated[str, Field(description="Module path starting with './' (e.g., './ChartPanel')")],
    remote_type: Annotated[str, Field(description="Federation type: 'vite-esm' or 'webpack'")] = "vite-esm",
    props: Annotated[Optional[Dict[str, Any]], Field(description="Props to pass to the MFE component")] = None,
    w: Annotated[int, Field(description="Grid width in columns (out of 100)")] = 50,
    h: Annotated[int, Field(description="Grid height in row units")] = 25,
) -> Dict[str, Any]:
    """Render a custom Module Federation microfrontend component on the dashboard.

    NOTE: This function is hidden from the LLM tool registry.
    Use render_custom_visualization for plugins listed in
    list_available_visualizations.
    """
    # Normalize module path — must start with './'
    normalized_module = module if module.startswith("./") else f"./{module.lstrip('/')}"

    return {
        "visualization": {
            "source": "Client Custom",
            "vizType": "custom",
            "args": {
                "url": url,
                "scope": scope,
                "module": normalized_module,
                "remoteType": remote_type,
                "initialData": props or {},
            },
            "w": w,
            "h": h,
        }
    }


# ---------------------------------------------------------------------------
# Client plugin rendering
# ---------------------------------------------------------------------------

def _validate_plugin_props(source: str, props: Dict) -> Optional[str]:
    """Validate props against a plugin's declared arg schema. Returns error string or None.

    When schema is non-empty:
    - Strips unknown props not in schema
    - Validates types for known props
    - Requires non-checkbox args

    When schema is empty: accepts any props (backward compat).
    """
    all_plugins = _get_all_plugins()
    plugin = next((p for p in all_plugins if p["source"] == source), None)
    if not plugin:
        available = [p["source"] for p in all_plugins]
        return f"Plugin '{source}' not found. Available: {available}"

    schema = plugin.get("args", {})

    # Empty schema: permissive mode (backward compat)
    if not schema:
        return None

    # Strip unknown props
    unknown = [k for k in props if k not in schema]
    if unknown:
        LOGGER.warning(
            "Stripping unknown props for '%s': %s (declared: %s)",
            source, unknown, list(schema.keys()),
        )
        for k in unknown:
            del props[k]

    # Validate declared args
    for arg_name, arg_spec in schema.items():
        value = props.get(arg_name)
        if value is None:
            continue
        if isinstance(arg_spec, list) and value not in arg_spec:
            return f"Invalid value '{value}' for '{arg_name}'. Must be one of: {arg_spec}"
        if isinstance(arg_spec, dict):
            # Rich schema: validate based on inner type field
            inner_type = arg_spec.get("type")
            if inner_type == "array" and not isinstance(value, list):
                return f"'{arg_name}' must be an array, got: {type(value).__name__}"
            if inner_type == "object" and not isinstance(value, dict):
                return f"'{arg_name}' must be an object, got: {type(value).__name__}"
            if inner_type == "string" and not isinstance(value, str):
                return f"'{arg_name}' must be a string, got: {type(value).__name__}"
            if inner_type == "number" and not isinstance(value, (int, float)):
                return f"'{arg_name}' must be a number, got: {type(value).__name__}"
            continue
        if arg_spec == "number" and not isinstance(value, (int, float)):
            return f"'{arg_name}' must be a number, got: {type(value).__name__}"
        if arg_spec == "text" and not isinstance(value, str):
            return f"'{arg_name}' must be a string, got: {type(value).__name__}"
        if arg_spec == "object" and not isinstance(value, dict):
            return f"'{arg_name}' must be an object, got: {type(value).__name__}"
        if arg_spec == "array" and not isinstance(value, list):
            return f"'{arg_name}' must be an array, got: {type(value).__name__}"

    # Check required args — rich schemas can declare required: false
    for arg_name, arg_spec in schema.items():
        if arg_name in props:
            continue
        # Rich schema objects: check required field (default: true)
        if isinstance(arg_spec, dict) and not arg_spec.get("required", True):
            continue
        # Simple type strings: checkbox is optional, everything else required
        if arg_spec == "checkbox":
            continue
        return f"Missing required arg: '{arg_name}'"

    return None


@mcp.tool(
    name="render_custom_visualization",
    description="Render a registered custom visualization component on the dashboard. Call list_available_visualizations first to see available custom plugins.",
    tags=["dashboard", "visualization", "custom"],
)
def render_custom_visualization(
    source: Annotated[str, Field(description="Client plugin source name from list_available_visualizations")],
    props: Annotated[Optional[Dict[str, Any]], Field(description="Props to pass to the plugin component. Check list_available_visualizations for each plugin's required args and valid values.")] = None,
    w: Annotated[int, Field(description="Grid width in columns (out of 100)")] = 50,
    h: Annotated[int, Field(description="Grid height in row units")] = 30,
) -> Dict[str, Any]:
    """Render a registered client plugin on the dashboard.

    ALWAYS use this tool for plugins listed in
    list_available_visualizations. This tool reads the correct URL, scope,
    module, and validates props against the plugin's declared arg schema.
    """
    safe_props = props or {}
    all_plugins = _get_all_plugins()

    LOGGER.info("render_custom_visualization called: source=%s, props=%s", source, safe_props)

    validation_error = _validate_plugin_props(source, safe_props)
    if validation_error:
        return {"error": validation_error}

    plugin = next((p for p in all_plugins if p["source"] == source), None)
    if plugin is None:
        available = [p["source"] for p in all_plugins]
        LOGGER.warning("Plugin '%s' not found. Available: %s", source, available)
        return {"error": f"Plugin '{source}' not found. Available: {available}"}

    # Runtime MFE plugins: return Module Federation coordinates.
    # The frontend resolves the remoteEntry.js URL (see chatbox.jsx handleResult).
    if plugin.get("type") == "client_custom_remote":
        viz_spec = {
            "source": "Client Custom",
            "vizType": "custom",
            "scope": plugin.get("scope"),
            "module": plugin.get("module"),
            "remoteType": plugin.get("remoteType", "vite-esm"),
            "args": safe_props,
            "w": w,
            "h": h,
        }
        if plugin.get("url"):
            viz_spec["url"] = plugin["url"]
        if plugin.get("dataKey"):
            viz_spec["dataKey"] = plugin["dataKey"]
        return {"visualization": viz_spec}

    # Build-time npm plugins: render via ClientModuleLoader
    return {
        "visualization": {
            "source": source,
            "vizType": "client_custom",
            "args": safe_props,
            "w": w,
            "h": h,
        }
    }


# ---------------------------------------------------------------------------
# Runtime plugin registration
# ---------------------------------------------------------------------------

@mcp.tool(
    name="register_runtime_plugin",
    description="Register a runtime MFE plugin so it appears in available visualizations and can be rendered with render_custom_visualization",
    tags=["dashboard", "plugin", "register"],
)
def register_runtime_plugin(
    url: Annotated[str, Field(description="URL to the remoteEntry.js file")],
    scope: Annotated[str, Field(description="Module Federation scope name")],
    module: Annotated[str, Field(description="Exposed module path (e.g., './MyPanel')")],
    label: Annotated[str, Field(description="Display name for the plugin")],
    remote_type: Annotated[str, Field(description="Remote type: 'vite-esm' or 'webpack'")] = "vite-esm",
    description: Annotated[str, Field(description="Human-readable description")] = "",
    group: Annotated[str, Field(description="Visualization group/category")] = "Custom",
    data_key: Annotated[str, Field(description="variableInputValues key this panel reads")] = "",
) -> Dict[str, Any]:
    """Register a runtime MFE plugin so it appears in available visualizations.

    The plugin is saved to the server-side registry and becomes immediately
    available via list_available_visualizations and render_custom_visualization.
    """
    LOGGER.info("register_runtime_plugin called: url=%s, scope=%s, module=%s, label=%s", url, scope, module, label)

    all_plugins = _get_all_plugins()
    key = f"{scope}/{module}"
    if any(f"{p.get('scope')}/{p.get('module')}" == key for p in all_plugins):
        LOGGER.warning("Plugin %s already registered, skipping", key)
        return {"error": f"Plugin {key} is already registered."}

    entry = {
        "id": str(uuid.uuid4()),
        "source": label.strip(),
        "url": url.strip(),
        "scope": scope.strip(),
        "module": module.strip(),
        "remoteType": remote_type,
        "label": label.strip(),
        "description": description,
        "group": group,
        "tags": [],
        "dataKey": data_key,
        "args": {},
        "type": "client_custom_remote",
    }

    registry_path = os.path.normpath(os.path.join(
        os.path.dirname(__file__), "..", "..", "..",
        "reactapp", "generated", "runtimePluginRegistry.json"
    ))
    runtime = _load_runtime_plugin_registry()
    runtime.append(entry)
    os.makedirs(os.path.dirname(registry_path), exist_ok=True)
    with open(registry_path, "w") as f:
        json.dump(runtime, f, indent=2)

    LOGGER.info("Registered plugin %s → %s (total runtime: %d)", key, label, len(runtime))
    return {"status": "registered", "plugin": entry}


# ---------------------------------------------------------------------------
# Discovery tools
# ---------------------------------------------------------------------------

@mcp.tool(
    name="list_available_visualizations",
    description="List all visualization types: native (charts, tables, maps), registered custom visualizations, and MFE components",
    tags=["discovery"],
)
def list_available_visualizations() -> Dict[str, Any]:
    """List all visualization types available for creating dashboard items.

    Returns built-in types (plotly, table, map, card, text, image),
    installed client plugins with argument schemas, and MFE rendering info.
    """
    return {
        "builtin": [
            {
                "type": "plotly",
                "name": "Plotly Chart",
                "tool": "create_plotly_chart",
                "description": "Interactive line/bar/scatter charts via Plotly.js",
                "prefer_native": True,
            },
            {
                "type": "table",
                "name": "Data Table",
                "tool": "create_data_table",
                "description": "Tabular data display with headers and rows",
                "prefer_native": True,
            },
            {
                "type": "map",
                "name": "Map",
                "tool": "create_map_visualization",
                "description": "OpenLayers map. Supports WMS, GeoJSON, KML, ESRI services, Image/Vector tiles, PMTiles",
                "prefer_native": True,
            },
            {
                "type": "card",
                "name": "Card",
                "tool": "create_card",
                "description": "Simple card with title, description, and data value",
                "prefer_native": True,
            },
            {
                "type": "image",
                "name": "Custom Image",
                "tool": "create_custom_image",
                "description": "Display an image from a URL",
                "prefer_native": True,
            },
            {
                "type": "text",
                "name": "Text",
                "tool": "create_text",
                "description": "Static text content",
                "prefer_native": True,
            },
        ],
        "client_plugins": [
            {
                "source": plugin["source"],
                "label": plugin.get("label", plugin["source"]),
                "group": plugin.get("group", "Client Plugins"),
                "description": plugin.get("description", ""),
                "tags": plugin.get("tags", []),
                "args_schema": _convert_plugin_args_to_schema(plugin.get("args", {})),
                "tool": "render_custom_visualization",
            }
            for plugin in _get_all_plugins()
        ],
        "mfe": {
            "tool": "render_custom_visualization",
            "description": "Module Federation components are rendered via render_custom_visualization. Use register_runtime_plugin to add new MFE plugins, then render them with render_custom_visualization.",
            "note": "The legacy render_mfe tool is hidden. Use render_custom_visualization instead.",
        },
        "variable_inputs": {
            "tool": "create_variable_input",
            "description": "Create interactive variable inputs (text, number, date, slider, checkbox). Other visualizations reference them with ${variable_name} syntax.",
        },
        "intake_plugins": {
            "tool": "list_intake_plugins",
            "description": "Python backend plugins installed via intake. Call list_intake_plugins to discover available plugins and their args, then use render_plugin to create visualizations.",
        },
    }


# ---------------------------------------------------------------------------
# Logging + Entry Point
# ---------------------------------------------------------------------------

def _configure_logging():
    level = os.getenv("TETHYSDASH_LOG_LEVEL", "INFO").upper()
    logging.basicConfig(
        level=getattr(logging, level, logging.INFO),
        format="%(asctime)s [%(name)s] %(levelname)s: %(message)s",
    )


if __name__ == "__main__":
    _configure_logging()
    port = int(os.getenv("TETHYSDASH_MCP_PORT", "9001"))
    LOGGER.info(f"Starting TethysDash MCP Server on 0.0.0.0:{port} with SSE transport")
    mcp.run(
        transport="sse",
        host="0.0.0.0",
        port=port,
        middleware=CORS_MIDDLEWARE,
    )
