"""
TethysDash MCP Server

Exposes tools for creating native TethysDash visualizations (Plotly charts,
tables, maps, cards, text) and rendering registered MFE components.

The LLM calls these tools to create dashboard grid items with inline data -
no backend API call needed. The chatbox dispatches the returned specs as
DOM events that DashboardLayout.js handles.

Usage:
    python -m tethysapp.tethysdash.mcp.tethysdash_mcp_server

Connects to chatbox via MCP SSE transport on port 9001.
"""

import logging
import os
import json
import uuid
from typing import Optional, Dict, Any, List
from typing_extensions import Annotated
from pydantic import Field
from fastmcp import FastMCP
from starlette.middleware import Middleware
from starlette.middleware.cors import CORSMiddleware
import requests as http_requests

mcp = FastMCP("TethysDash MCP Server")
LOGGER = logging.getLogger("tethysdash.mcp")
TETHYSDASH_BASE_URL = os.getenv("TETHYSDASH_BASE_URL", "http://localhost:8080/apps/tethysdash")

CORS_MIDDLEWARE = [
    Middleware(
        CORSMiddleware,
        allow_origins=["*"],
        allow_methods=["*"],
        allow_headers=["*"],
    )
]

# ---------------------------------------------------------------------------
# Client plugin registry (loaded from collectClientPlugins.js output)
# ---------------------------------------------------------------------------

def _load_client_plugin_registry() -> List[Dict[str, Any]]:
    """Load the client plugin registry generated by collectClientPlugins.js."""
    registry_path = os.path.normpath(os.path.join(
        os.path.dirname(__file__), "..", "..", "..",
        "reactapp", "generated", "clientPluginRegistry.json"
    ))
    try:
        with open(registry_path, "r") as f:
            registry = json.load(f)
        LOGGER.info("Loaded %d client plugin(s) from %s", len(registry), registry_path)
        return registry
    except FileNotFoundError:
        LOGGER.warning("Client plugin registry not found: %s", registry_path)
        return []
    except json.JSONDecodeError as e:
        LOGGER.warning("Invalid JSON in client plugin registry: %s", e)
        return []


CLIENT_PLUGIN_REGISTRY = _load_client_plugin_registry()


def _load_runtime_plugin_registry() -> List[Dict[str, Any]]:
    """Load the runtime plugin registry synced from browser localStorage."""
    registry_path = os.path.normpath(os.path.join(
        os.path.dirname(__file__), "..", "..", "..",
        "reactapp", "generated", "runtimePluginRegistry.json"
    ))
    try:
        with open(registry_path, "r") as f:
            registry = json.load(f)
        LOGGER.info("Loaded %d runtime plugin(s) from %s", len(registry), registry_path)
        return registry
    except FileNotFoundError:
        return []
    except json.JSONDecodeError as e:
        LOGGER.warning("Invalid JSON in runtime plugin registry: %s", e)
        return []


def _get_all_plugins() -> List[Dict[str, Any]]:
    """Return combined static + runtime registries, re-reading runtime from disk."""
    runtime = _load_runtime_plugin_registry()
    combined = CLIENT_PLUGIN_REGISTRY + runtime
    LOGGER.info(
        "Plugin registries: %d static + %d runtime = %d total",
        len(CLIENT_PLUGIN_REGISTRY), len(runtime), len(combined),
    )
    return combined


def _convert_arg_to_schema(arg_name: str, arg_spec) -> Dict[str, Any]:
    """Convert a tethysdash plugin arg type to a structured schema."""
    if isinstance(arg_spec, list):
        return {"type": "string", "enum": arg_spec}
    if arg_spec == "text":
        return {"type": "string"}
    if arg_spec == "number":
        return {"type": "number"}
    if arg_spec == "checkbox":
        return {"type": "boolean", "default": False}
    if arg_spec == "object":
        return {"type": "object"}
    if arg_spec == "array":
        return {"type": "array"}
    if isinstance(arg_spec, dict):
        return arg_spec  # pass through rich declarations as-is
    return {"type": "string", "description": f"Input type: {arg_spec}"}


def _convert_plugin_args_to_schema(args: Dict) -> Dict[str, Any]:
    """Convert all args for a plugin to structured schemas."""
    return {name: _convert_arg_to_schema(name, spec) for name, spec in args.items()}


# ---------------------------------------------------------------------------
# Built-in visualization tools
# ---------------------------------------------------------------------------

@mcp.tool()
def create_plotly_chart(
    data: Annotated[List[Dict[str, Any]], Field(description="Plotly trace objects. Each dict should have 'x', 'y', and optionally 'type', 'name', 'mode', etc.")],
    layout: Annotated[Optional[Dict[str, Any]], Field(description="Plotly layout object with title, axis labels, etc.")] = None,
    config: Annotated[Optional[Dict[str, Any]], Field(description="Plotly config object (responsive, displaylogo, etc.)")] = None,
    title: Annotated[Optional[str], Field(description="Chart title (shorthand - added to layout.title)")] = None,
    w: Annotated[int, Field(description="Grid width in columns (out of 100)")] = 50,
    h: Annotated[int, Field(description="Grid height in row units (each unit ~10px at 1920px)")] = 40,
) -> Dict[str, Any]:
    """Create a Plotly chart visualization on the dashboard.

    Returns a visualization spec that the chatbox dispatches as a grid item.
    The chart renders using TethysDash's native BasePlot component.
    """
    final_layout = layout or {}
    if title and "title" not in final_layout:
        final_layout["title"] = title

    final_config = config or {"responsive": True, "displaylogo": False}

    return {
        "visualization": {
            "source": "Inline Plotly",
            "vizType": "plotly",
            "inlineData": {
                "data": data,
                "layout": final_layout,
                "config": final_config,
            },
            "w": w,
            "h": h,
        }
    }


@mcp.tool()
def create_data_table(
    data: Annotated[List[Dict[str, Any]], Field(description="Array of row objects, e.g. [{'col1': 'val1', 'col2': 'val2'}, ...]")],
    title: Annotated[Optional[str], Field(description="Table title")] = None,
    subtitle: Annotated[Optional[str], Field(description="Table subtitle")] = None,
    w: Annotated[int, Field(description="Grid width in columns (out of 100)")] = 50,
    h: Annotated[int, Field(description="Grid height in row units (each unit ~10px at 1920px)")] = 35,
) -> Dict[str, Any]:
    """Create a data table visualization on the dashboard.

    Returns a visualization spec that renders using TethysDash's native DataTable component.
    """
    return {
        "visualization": {
            "source": "Inline Table",
            "vizType": "table",
            "inlineData": {
                "data": data,
                "title": title or "",
                "subtitle": subtitle or "",
            },
            "w": w,
            "h": h,
        }
    }


@mcp.tool()
def create_card(
    title: Annotated[str, Field(description="Card title")],
    description: Annotated[Optional[str], Field(description="Card description text")] = None,
    data: Annotated[Optional[Any], Field(description="Card data (value, metric, etc.)")] = None,
    w: Annotated[int, Field(description="Grid width in columns (out of 100)")] = 25,
    h: Annotated[int, Field(description="Grid height in row units")] = 15,
) -> Dict[str, Any]:
    """Create a card visualization on the dashboard.

    Cards display a title, description, and optional data value.
    Renders using TethysDash's native Card component.
    """
    return {
        "visualization": {
            "source": "Inline Card",
            "vizType": "card",
            "inlineData": {
                "title": title,
                "description": description or "",
                "data": data,
            },
            "w": w,
            "h": h,
        }
    }


@mcp.tool()
def create_text(
    text: Annotated[str, Field(description="Text content to display")],
    w: Annotated[int, Field(description="Grid width in columns (out of 100)")] = 50,
    h: Annotated[int, Field(description="Grid height in row units")] = 15,
) -> Dict[str, Any]:
    """Create a text visualization on the dashboard.

    Renders using TethysDash's native Text component.
    """
    return {
        "visualization": {
            "source": "Inline Text",
            "vizType": "text",
            "inlineData": {
                "text": text,
            },
            "w": w,
            "h": h,
        }
    }


@mcp.tool()
def create_custom_image(
    image_url: Annotated[str, Field(description="URL of the image to display (http/https URL, data URI, or S3 path)")],
    alt_text: Annotated[Optional[str], Field(description="Alt text for accessibility")] = None,
    w: Annotated[int, Field(description="Grid width in columns (out of 100)")] = 50,
    h: Annotated[int, Field(description="Grid height in row units (each unit ~10px at 1920px)")] = 30,
) -> Dict[str, Any]:
    """Create a custom image visualization on the dashboard.

    Displays an image from a URL. Renders using TethysDash's native Image component.
    """
    return {
        "visualization": {
            "source": "Inline Image",
            "vizType": "image",
            "inlineData": {
                "source": image_url,
                "alt": alt_text or "custom_image",
            },
            "w": w,
            "h": h,
        }
    }


BASE_MAPS = {
    "light_gray": "https://server.arcgisonline.com/arcgis/rest/services/Canvas/World_Light_Gray_Base/MapServer",
    "dark_gray": "https://server.arcgisonline.com/arcgis/rest/services/Canvas/World_Dark_Gray_Base/MapServer",
    "topo": "https://server.arcgisonline.com/arcgis/rest/services/World_Topo_Map/MapServer",
    "imagery": "https://server.arcgisonline.com/arcgis/rest/services/World_Imagery/MapServer",
    "streets": "https://server.arcgisonline.com/arcgis/rest/services/World_Street_Map/MapServer",
}

DEFAULT_BASE_MAP = BASE_MAPS["light_gray"]


@mcp.tool()
def create_map_visualization(
    layers: Annotated[List[Dict[str, Any]], Field(description=(
        "Array of map layer objects. Each layer must have this structure: "
        '{"configuration": {"type": "<LayerType>", "props": {"name": "<display name>", '
        '"source": {"type": "<SourceType>", "props": {<source-specific>}}}}}. '
        "Layer types: ImageLayer, VectorLayer, WebGLTile, VectorTileLayer. "
        "Source types: WMS, GeoJSON, KML, 'Image Tile', 'Vector Tile', "
        "'ESRI Image and Map Service', 'ESRI Feature Service', 'PMTiles Raster', 'PMTiles Vector'. "
        "WMS example: {\"configuration\": {\"type\": \"ImageLayer\", \"props\": {\"name\": \"States\", "
        "\"source\": {\"type\": \"WMS\", \"props\": {\"url\": \"https://host/wms\", "
        "\"params\": {\"LAYERS\": \"workspace:layer\"}}}}}}. "
        "GeoJSON example: {\"configuration\": {\"type\": \"VectorLayer\", \"props\": {\"name\": \"Features\", "
        "\"source\": {\"type\": \"GeoJSON\", \"props\": {}, \"geojson\": <GeoJSON object>}}}}."
    ))],
    base_map: Annotated[Optional[str], Field(description=(
        "Base map tile service URL or shorthand name. "
        "Shorthand names: 'light_gray', 'dark_gray', 'topo', 'imagery', 'streets'. "
        "Or provide a full ArcGIS MapServer URL. Set to null for no base map."
    ))] = "light_gray",
    map_extent: Annotated[Optional[str], Field(description=(
        "Map extent as a comma-separated string. "
        "Bounding box format: 'minX,minY,maxX,maxY' (e.g., '-125,24,-66,50' for CONUS). "
        "Center+zoom format: 'lon,lat,zoom' (e.g., '-98.5,39.8,4' for US center). "
        "Set to null for default extent."
    ))] = None,
    layer_control: Annotated[bool, Field(description="Show the layer control panel")] = True,
    map_drawing: Annotated[Optional[Dict[str, Any]], Field(description=(
        "Drawing interaction config. Null to disable. "
        "Format: {\"options\": [\"Point\", \"LineString\", \"Polygon\", \"Box\", \"Circle\"], \"limit\": 10}."
    ))] = None,
    w: Annotated[int, Field(description="Grid width in columns (out of 100)")] = 50,
    h: Annotated[int, Field(description="Grid height in row units (each unit ~10px at 1920px)")] = 45,
) -> Dict[str, Any]:
    """Create an OpenLayers map visualization on the dashboard.

    Supports WMS, GeoJSON, KML, ESRI services, Image/Vector tiles, and PMTiles.
    Renders using TethysDash's native MapVisualization component.
    """
    resolved_base_map = BASE_MAPS.get(base_map, base_map) if base_map else None

    return {
        "visualization": {
            "source": "Inline Map",
            "vizType": "map",
            "inlineData": {
                "baseMap": resolved_base_map,
                "layers": layers,
                "layerControl": layer_control,
                "map_extent": {"extent": map_extent} if map_extent else None,
                "mapConfig": {"style": {"width": "100%", "height": "100%"}},
                "mapDrawing": map_drawing,
            },
            "w": w,
            "h": h,
        }
    }


# ---------------------------------------------------------------------------
# Variable input + intake plugin tools
# ---------------------------------------------------------------------------

@mcp.tool()
def create_variable_input(
    variable_name: Annotated[str, Field(description="Variable name used in ${...} references by other visualizations")],
    variable_type: Annotated[str, Field(description="Input type: 'text', 'number', 'checkbox', 'date', or 'slider'")] = "text",
    initial_value: Annotated[str, Field(description="Default value for the variable input")] = "",
    w: Annotated[int, Field(description="Grid width in columns (out of 100)")] = 20,
    h: Annotated[int, Field(description="Grid height in row units")] = 5,
) -> Dict[str, Any]:
    """Create a variable input on the dashboard.

    Variable inputs are interactive controls (text fields, dropdowns, sliders)
    that other visualizations can reference using ${variable_name} syntax.
    When the user changes the input, all linked visualizations auto-refresh.

    Example: create_variable_input(variable_name="gauge_id", variable_type="text", initial_value="XSGEW")
    Then use render_intake_plugin(source="my_plugin", args={"gauge_id": "${gauge_id}"})
    """
    valid_types = ["text", "number", "checkbox", "date", "slider"]
    if variable_type not in valid_types:
        return {"error": f"Invalid variable_type '{variable_type}'. Must be one of: {valid_types}"}

    LOGGER.info("create_variable_input: name=%s, type=%s, initial=%s", variable_name, variable_type, initial_value)

    return {
        "visualization": {
            "source": "Variable Input",
            "vizType": "variableInput",
            "args": {
                "variable_name": variable_name,
                "variable_options_source": variable_type,
                "initial_value": initial_value,
            },
            "w": w,
            "h": h,
        }
    }


@mcp.tool()
def list_intake_plugins() -> Dict[str, Any]:
    """List all installed Python intake-driver plugins available in TethysDash.

    Returns plugin names, types, argument schemas, groups, and descriptions.
    Use this to discover what backend plugins are available before calling
    render_intake_plugin.

    Note: Requires the TethysDash Django server to be running.
    """
    try:
        response = http_requests.get(
            f"{TETHYSDASH_BASE_URL}/visualizations/list/",
            timeout=10,
        )
        response.raise_for_status()
        data = response.json()

        LOGGER.info("list_intake_plugins: fetched %d groups from Django API", len(data) if isinstance(data, list) else 1)

        return {"intake_plugins": data}
    except http_requests.RequestException as e:
        LOGGER.error("Failed to fetch intake plugins from Django: %s", e)
        return {"error": f"Failed to fetch intake plugins from TethysDash: {e}"}


@mcp.tool()
def render_intake_plugin(
    source: Annotated[str, Field(description="Intake plugin source name from list_intake_plugins (e.g., 'time_series_maker')")],
    args: Annotated[Dict[str, Any], Field(description="Plugin arguments. Use ${variable_name} syntax to reference dashboard variable inputs. Example: {\"gauge_id\": \"${my_gauge}\"}")],
    w: Annotated[int, Field(description="Grid width in columns (out of 100)")] = 50,
    h: Annotated[int, Field(description="Grid height in row units")] = 25,
) -> Dict[str, Any]:
    """Create a visualization using a Python intake-driver plugin.

    The visualization calls the TethysDash backend API with the given args.
    Args can reference variable inputs using ${variable_name} syntax —
    when the referenced variable changes, the visualization auto-refreshes.

    Call list_intake_plugins first to see available plugins and their args.

    Example: render_intake_plugin(
        source="time_series_maker",
        args={"gauge_id": "${gauge_id}", "start_date": "2024-01-01"}
    )
    """
    LOGGER.info("render_intake_plugin: source=%s, args=%s", source, args)

    return {
        "visualization": {
            "source": source,
            "vizType": "intake_plugin",
            "args": args,
            "w": w,
            "h": h,
        }
    }


# ---------------------------------------------------------------------------
# MFE rendering tools
# ---------------------------------------------------------------------------

@mcp.tool()
def render_mfe(
    url: Annotated[str, Field(description="URL to the MFE's remoteEntry.js")],
    scope: Annotated[str, Field(description="Module Federation scope name")],
    module: Annotated[str, Field(description="Module path starting with './' (e.g., './ChartPanel')")],
    remote_type: Annotated[str, Field(description="Federation type: 'vite-esm' or 'webpack'")] = "vite-esm",
    props: Annotated[Optional[Dict[str, Any]], Field(description="Props to pass to the MFE component")] = None,
    w: Annotated[int, Field(description="Grid width in columns (out of 100)")] = 50,
    h: Annotated[int, Field(description="Grid height in row units")] = 25,
) -> Dict[str, Any]:
    """Render a custom Module Federation microfrontend component on the dashboard.

    IMPORTANT: Prefer render_client_plugin for any plugin listed in
    list_available_visualizations. Only use render_mfe for ad-hoc MFEs
    not in the registry.
    """
    # Normalize module path — must start with './'
    normalized_module = module if module.startswith("./") else f"./{module.lstrip('/')}"

    return {
        "visualization": {
            "source": "Client Custom",
            "vizType": "custom",
            "args": {
                "url": url,
                "scope": scope,
                "module": normalized_module,
                "remoteType": remote_type,
                "initialData": props or {},
            },
            "w": w,
            "h": h,
        }
    }


# ---------------------------------------------------------------------------
# Client plugin rendering
# ---------------------------------------------------------------------------

def _validate_plugin_props(source: str, props: Dict) -> Optional[str]:
    """Validate props against a plugin's declared arg schema. Returns error string or None.

    When schema is non-empty:
    - Strips unknown props not in schema
    - Validates types for known props
    - Requires non-checkbox args

    When schema is empty: accepts any props (backward compat).
    """
    all_plugins = _get_all_plugins()
    plugin = next((p for p in all_plugins if p["source"] == source), None)
    if not plugin:
        available = [p["source"] for p in all_plugins]
        return f"Plugin '{source}' not found. Available: {available}"

    schema = plugin.get("args", {})

    # Empty schema: permissive mode (backward compat)
    if not schema:
        return None

    # Strip unknown props
    unknown = [k for k in props if k not in schema]
    if unknown:
        LOGGER.warning(
            "Stripping unknown props for '%s': %s (declared: %s)",
            source, unknown, list(schema.keys()),
        )
        for k in unknown:
            del props[k]

    # Validate declared args
    for arg_name, arg_spec in schema.items():
        value = props.get(arg_name)
        if value is None:
            continue
        if isinstance(arg_spec, list) and value not in arg_spec:
            return f"Invalid value '{value}' for '{arg_name}'. Must be one of: {arg_spec}"
        if isinstance(arg_spec, dict):
            # Rich schema: validate based on inner type field
            inner_type = arg_spec.get("type")
            if inner_type == "array" and not isinstance(value, list):
                return f"'{arg_name}' must be an array, got: {type(value).__name__}"
            if inner_type == "object" and not isinstance(value, dict):
                return f"'{arg_name}' must be an object, got: {type(value).__name__}"
            if inner_type == "string" and not isinstance(value, str):
                return f"'{arg_name}' must be a string, got: {type(value).__name__}"
            if inner_type == "number" and not isinstance(value, (int, float)):
                return f"'{arg_name}' must be a number, got: {type(value).__name__}"
            continue
        if arg_spec == "number" and not isinstance(value, (int, float)):
            return f"'{arg_name}' must be a number, got: {type(value).__name__}"
        if arg_spec == "text" and not isinstance(value, str):
            return f"'{arg_name}' must be a string, got: {type(value).__name__}"
        if arg_spec == "object" and not isinstance(value, dict):
            return f"'{arg_name}' must be an object, got: {type(value).__name__}"
        if arg_spec == "array" and not isinstance(value, list):
            return f"'{arg_name}' must be an array, got: {type(value).__name__}"

    # Check required args — rich schemas can declare required: false
    for arg_name, arg_spec in schema.items():
        if arg_name in props:
            continue
        # Rich schema objects: check required field (default: true)
        if isinstance(arg_spec, dict) and not arg_spec.get("required", True):
            continue
        # Simple type strings: checkbox is optional, everything else required
        if arg_spec == "checkbox":
            continue
        return f"Missing required arg: '{arg_name}'"

    return None


@mcp.tool()
def render_client_plugin(
    source: Annotated[str, Field(description="Client plugin source name from list_available_visualizations")],
    props: Annotated[Optional[Dict[str, Any]], Field(description="Props to pass to the plugin component. Check list_available_visualizations for each plugin's required args and valid values.")] = None,
    w: Annotated[int, Field(description="Grid width in columns (out of 100)")] = 50,
    h: Annotated[int, Field(description="Grid height in row units")] = 30,
) -> Dict[str, Any]:
    """Render a registered client plugin on the dashboard.

    ALWAYS use this tool (not render_mfe) for plugins listed in
    list_available_visualizations. This tool reads the correct URL, scope,
    module, and validates props against the plugin's declared arg schema.
    """
    safe_props = props or {}
    all_plugins = _get_all_plugins()

    LOGGER.info("render_client_plugin called: source=%s, props=%s", source, safe_props)

    validation_error = _validate_plugin_props(source, safe_props)
    if validation_error:
        return {"error": validation_error}

    plugin = next((p for p in all_plugins if p["source"] == source), None)
    if plugin is None:
        available = [p["source"] for p in all_plugins]
        LOGGER.warning("Plugin '%s' not found. Available: %s", source, available)
        return {"error": f"Plugin '{source}' not found. Available: {available}"}

    # Runtime MFE plugins: return Module Federation coordinates.
    # The frontend resolves the remoteEntry.js URL (see chatbox.jsx handleResult).
    if plugin.get("type") == "client_custom_remote":
        viz_spec = {
            "source": "Client Custom",
            "vizType": "custom",
            "scope": plugin.get("scope"),
            "module": plugin.get("module"),
            "remoteType": plugin.get("remoteType", "vite-esm"),
            "args": safe_props,
            "w": w,
            "h": h,
        }
        if plugin.get("url"):
            viz_spec["url"] = plugin["url"]
        if plugin.get("dataKey"):
            viz_spec["dataKey"] = plugin["dataKey"]
        return {"visualization": viz_spec}

    # Build-time npm plugins: render via ClientModuleLoader
    return {
        "visualization": {
            "source": source,
            "vizType": "client_custom",
            "args": safe_props,
            "w": w,
            "h": h,
        }
    }


# ---------------------------------------------------------------------------
# Runtime plugin registration
# ---------------------------------------------------------------------------

@mcp.tool()
def register_runtime_plugin(
    url: Annotated[str, Field(description="URL to the remoteEntry.js file")],
    scope: Annotated[str, Field(description="Module Federation scope name")],
    module: Annotated[str, Field(description="Exposed module path (e.g., './MyPanel')")],
    label: Annotated[str, Field(description="Display name for the plugin")],
    remote_type: Annotated[str, Field(description="Remote type: 'vite-esm' or 'webpack'")] = "vite-esm",
    description: Annotated[str, Field(description="Human-readable description")] = "",
    group: Annotated[str, Field(description="Visualization group/category")] = "Custom",
    data_key: Annotated[str, Field(description="variableInputValues key this panel reads")] = "",
) -> Dict[str, Any]:
    """Register a runtime MFE plugin so it appears in available visualizations.

    The plugin is saved to the server-side registry and becomes immediately
    available via list_available_visualizations and render_client_plugin.
    """
    LOGGER.info("register_runtime_plugin called: url=%s, scope=%s, module=%s, label=%s", url, scope, module, label)

    all_plugins = _get_all_plugins()
    key = f"{scope}/{module}"
    if any(f"{p.get('scope')}/{p.get('module')}" == key for p in all_plugins):
        LOGGER.warning("Plugin %s already registered, skipping", key)
        return {"error": f"Plugin {key} is already registered."}

    entry = {
        "id": str(uuid.uuid4()),
        "source": label.strip(),
        "url": url.strip(),
        "scope": scope.strip(),
        "module": module.strip(),
        "remoteType": remote_type,
        "label": label.strip(),
        "description": description,
        "group": group,
        "tags": [],
        "dataKey": data_key,
        "args": {},
        "type": "client_custom_remote",
    }

    registry_path = os.path.normpath(os.path.join(
        os.path.dirname(__file__), "..", "..", "..",
        "reactapp", "generated", "runtimePluginRegistry.json"
    ))
    runtime = _load_runtime_plugin_registry()
    runtime.append(entry)
    os.makedirs(os.path.dirname(registry_path), exist_ok=True)
    with open(registry_path, "w") as f:
        json.dump(runtime, f, indent=2)

    LOGGER.info("Registered plugin %s → %s (total runtime: %d)", key, label, len(runtime))
    return {"status": "registered", "plugin": entry}


# ---------------------------------------------------------------------------
# Discovery tools
# ---------------------------------------------------------------------------

@mcp.tool()
def list_available_visualizations() -> Dict[str, Any]:
    """List all visualization types available for creating dashboard items.

    Returns built-in types (plotly, table, map, card, text, image),
    installed client plugins with argument schemas, and MFE rendering info.
    """
    return {
        "builtin": [
            {
                "type": "plotly",
                "name": "Plotly Chart",
                "tool": "create_plotly_chart",
                "description": "Interactive line/bar/scatter charts via Plotly.js",
                "prefer_native": True,
            },
            {
                "type": "table",
                "name": "Data Table",
                "tool": "create_data_table",
                "description": "Tabular data display with headers and rows",
                "prefer_native": True,
            },
            {
                "type": "map",
                "name": "Map",
                "tool": "create_map_visualization",
                "description": "OpenLayers map. Supports WMS, GeoJSON, KML, ESRI services, Image/Vector tiles, PMTiles",
                "prefer_native": True,
            },
            {
                "type": "card",
                "name": "Card",
                "tool": "create_card",
                "description": "Simple card with title, description, and data value",
                "prefer_native": True,
            },
            {
                "type": "image",
                "name": "Custom Image",
                "tool": "create_custom_image",
                "description": "Display an image from a URL",
                "prefer_native": True,
            },
            {
                "type": "text",
                "name": "Text",
                "tool": "create_text",
                "description": "Static text content",
                "prefer_native": True,
            },
        ],
        "client_plugins": [
            {
                "source": plugin["source"],
                "label": plugin.get("label", plugin["source"]),
                "group": plugin.get("group", "Client Plugins"),
                "description": plugin.get("description", ""),
                "tags": plugin.get("tags", []),
                "args_schema": _convert_plugin_args_to_schema(plugin.get("args", {})),
                "tool": "render_client_plugin",
            }
            for plugin in _get_all_plugins()
        ],
        "mfe": {
            "tool": "render_mfe",
            "description": "Render any Module Federation component by providing url, scope, and module",
        },
        "variable_inputs": {
            "tool": "create_variable_input",
            "description": "Create interactive variable inputs (text, number, date, slider, checkbox). Other visualizations reference them with ${variable_name} syntax.",
        },
        "intake_plugins": {
            "tool": "list_intake_plugins",
            "description": "Python backend plugins installed via intake. Call list_intake_plugins to discover available plugins and their args, then use render_intake_plugin to create visualizations.",
        },
    }


# ---------------------------------------------------------------------------
# Logging + Entry Point
# ---------------------------------------------------------------------------

def _configure_logging():
    level = os.getenv("TETHYSDASH_LOG_LEVEL", "INFO").upper()
    logging.basicConfig(
        level=getattr(logging, level, logging.INFO),
        format="%(asctime)s [%(name)s] %(levelname)s: %(message)s",
    )


if __name__ == "__main__":
    _configure_logging()
    port = int(os.getenv("TETHYSDASH_MCP_PORT", "9001"))
    LOGGER.info(f"Starting TethysDash MCP Server on 0.0.0.0:{port} with SSE transport")
    mcp.run(
        transport="sse",
        host="0.0.0.0",
        port=port,
        middleware=CORS_MIDDLEWARE,
    )
