"""Shared loaders for the webpack-built client plugin registries.

The registries are JSON files under ``reactapp/generated/`` produced at build
time by ``scripts/collectClientPlugins.js`` (``clientPluginRegistry.json``)
and persisted from browser state (``runtimePluginRegistry.json``).

Both the MCP server (``tethysdash_mcp_server.py``) and the per-source-whitelist
resolver (``editable_schemas_plugin.py``) need to read these. Keeping the
loaders in a single module avoids a circular import between the two.

Returned shape for both registries: ``List[Dict[str, Any]]`` — a list of
plugin entries, NOT a dict keyed by source. Consumers that need lookup by
source should iterate or build their own lookup.
"""

from __future__ import annotations

import json
import logging
import os
from typing import Any, Dict, List

LOGGER = logging.getLogger(__name__)

_CLIENT_REGISTRY_PATH = os.path.normpath(
    os.path.join(
        os.path.dirname(__file__),
        "..",
        "..",
        "reactapp",
        "generated",
        "clientPluginRegistry.json",
    )
)

_RUNTIME_REGISTRY_PATH = os.path.normpath(
    os.path.join(
        os.path.dirname(__file__),
        "..",
        "..",
        "reactapp",
        "generated",
        "runtimePluginRegistry.json",
    )
)


def load_client_plugin_registry() -> List[Dict[str, Any]]:
    """Load the build-time client plugin registry.

    Generated by ``scripts/collectClientPlugins.js`` at webpack build time
    from npm packages declaring ``tethysdash.clientPlugins`` in their
    ``package.json``. Treated as a trusted server-side source.
    """
    try:
        with open(_CLIENT_REGISTRY_PATH, "r") as f:
            registry = json.load(f)
        LOGGER.info(
            "Loaded %d client plugin(s) from %s",
            len(registry),
            _CLIENT_REGISTRY_PATH,
        )
        return registry
    except FileNotFoundError:
        LOGGER.warning(
            "Client plugin registry not found: %s", _CLIENT_REGISTRY_PATH
        )
        return []
    except json.JSONDecodeError as e:
        LOGGER.warning("Invalid JSON in client plugin registry: %s", e)
        return []


def load_runtime_plugin_registry() -> List[Dict[str, Any]]:
    """Load the runtime plugin registry synced from browser localStorage."""
    try:
        with open(_RUNTIME_REGISTRY_PATH, "r") as f:
            registry = json.load(f)
        LOGGER.info(
            "Loaded %d runtime plugin(s) from %s",
            len(registry),
            _RUNTIME_REGISTRY_PATH,
        )
        return registry
    except FileNotFoundError:
        return []
    except json.JSONDecodeError as e:
        LOGGER.warning("Invalid JSON in runtime plugin registry: %s", e)
        return []
