/**
 * collectClientPlugins.js
 *
 * Scans npm dependencies for packages that declare tethysdash client plugins
 * via a "tethysdash.clientPlugins" field in their package.json.
 *
 * Mirrors the Python-side collect_plugin_static.py pattern for intake drivers.
 *
 * Outputs:
 *   - reactapp/generated/clientPluginRegistry.json  (metadata for AppLoader)
 *   - reactapp/generated/clientPluginImports.js     (static import map for webpack)
 */
const fs = require("fs");
const path = require("path");

function discoverClientPlugins() {
  const pkgJsonPath = path.resolve(__dirname, "../package.json");
  const pkg = JSON.parse(fs.readFileSync(pkgJsonPath, "utf-8"));
  const allDeps = { ...pkg.dependencies, ...pkg.devDependencies };
  const registry = [];

  for (const depName of Object.keys(allDeps)) {
    try {
      const depPkgPath = require.resolve(`${depName}/package.json`);
      const depPkg = JSON.parse(fs.readFileSync(depPkgPath, "utf-8"));

      if (depPkg.tethysdash && Array.isArray(depPkg.tethysdash.clientPlugins)) {
        for (const plugin of depPkg.tethysdash.clientPlugins) {
          if (!plugin.source || !plugin.module) {
            console.warn(
              `  Skipping invalid client plugin in ${depName}: missing source or module`
            );
            continue;
          }
          registry.push({
            source: plugin.source,
            label: plugin.label || plugin.source,
            group: plugin.group || "Client Plugins",
            type: plugin.type || "client_custom",
            module: plugin.module,
            tags: plugin.tags || [],
            description: plugin.description || "",
            args: plugin.args || {},
            packageName: depName,
          });
        }
      }
    } catch (e) {
      // Package doesn't have a resolvable package.json — skip
    }
  }

  const outDir = path.resolve(__dirname, "../reactapp/generated");
  fs.mkdirSync(outDir, { recursive: true });

  // Write the JSON registry (used by AppLoader for visualization list)
  fs.writeFileSync(
    path.join(outDir, "clientPluginRegistry.json"),
    JSON.stringify(registry, null, 2)
  );

  // Generate the static import map (used by ClientModuleLoader at build time)
  // Each entry maps a source name to a dynamic import() with a literal path
  // so that webpack can resolve and code-split the modules at build time.
  const importEntries = registry.map((plugin) => {
    const importPath = `${plugin.packageName}/${plugin.module}`.replace(
      /^\.\//,
      ""
    );
    return `  ${JSON.stringify(plugin.source)}: () => import(${JSON.stringify(importPath)})`;
  });

  const importMapContent = [
    "// Auto-generated by collectClientPlugins.js — do not edit manually",
    "const clientPluginImports = {",
    importEntries.join(",\n"),
    "};",
    "",
    "export default clientPluginImports;",
    "",
  ].join("\n");

  fs.writeFileSync(path.join(outDir, "clientPluginImports.js"), importMapContent);

  console.log(
    `[collectClientPlugins] Discovered ${registry.length} client plugin(s)`
  );
}

discoverClientPlugins();
